## Section 0: Imports & Setup

In [1]:
#!/usr/bin/env python
# coding: utf-8
"""
Experiment 2 — Statistical Analysis (v3, fixed for pymer4 0.9.2 API)
=========================================
Preprocessing
-------------
1. order:  rescaled  1/2 → 0/1  (subtract 1, stored as order_c)
2. rating: centred only (subtract grand mean), NOT z-scored  →  rating_cen

Model structure (per outcome)
------------------------------
  Null:        outcome ~ 1 + RE
  Additive:    outcome ~ IVs + covariates + RE
  Interactive: outcome ~ IVs + all 2-way interactions + covariates + RE

Random effects
--------------
  Max: (1 + source_test | trace)   ← tested on each interactive model
  Red: (1 | trace)                  ← fallback if max is singular
  RE selection: LRT (interactive_max vs interactive_red)

Model comparisons  (LRT throughout)
------------------------------------
  Step 1 — RE:  interactive_max vs interactive_red
  Step 2 — FE:  null vs additive        (same RE as step 1 winner)
  Step 3 — FE:  additive vs interactive (same RE)

Outcomes
--------
  1.   RH (perceived)     binomial GLMM   logit
  2.   Accuracy           binomial GLMM   logit   all trials
  2P.  Accuracy-P         binomial GLMM   logit   perceived + RH predictor
  3.   Rating             Gaussian LMM    identity all trials
  3P.  Rating-P           Gaussian LMM    identity perceived + RH predictor
  4.   Confidence         Gaussian LMM    identity all trials
  4P.  Confidence-P       Gaussian LMM    identity perceived + RH predictor
  5.   Gamma              Gaussian LMM    identity trace-level
  5P.  Gamma-P            Gaussian LMM    identity trace-level, perceived + rh_mean

Covariates (included in additive & interactive, not null)
---------------------------------------------------------
  rating_cen  — mean-centred associative rating
  order_c     — presentation order (0/1)
  model       — LLM architecture (6 levels)

Post-hoc (on best interactive model per outcome)
-------------------------------------------------
  • Pairwise emmeans: source_test, fb_exp, setsize, model
  • Interaction contrasts: source_test × fb_exp  (H3)
  • Covariate slopes: rating_cen, order_c  (extracted from FE table)
"""

# ─────────────────────────────────────────────────────────────────────────────
# 0. Imports & setup
# ─────────────────────────────────────────────────────────────────────────────
import re
import gc
import warnings, os
import numpy as np
import pandas as pd
import polars as pl
import matplotlib
matplotlib.use('Agg')   # non-interactive backend — no GUI, no segfault
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from scipy import stats
from scipy.stats import shapiro
from IPython.display import display, Markdown

import rmllm
from rmllm import gamma as gamma_mod

# pymer4 ≥ 0.9 API
from pymer4.models import lmer, glmer, compare

# rpy2 — DHARMa diagnostics only
# pandas2ri.activate() removed: deprecated/raises in rpy2 ≥ 3.5
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr
from rpy2.robjects.conversion import localconverter

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)
np.random.seed(42)


def _r_pkg(name):
    try:
        return importr(name)
    except Exception:
        warnings.warn(f"R package '{name}' not available — some diagnostics skipped.")
        return None

_DHARMa  = _r_pkg("DHARMa")
_stats_r = importr("stats")
_base_r  = importr("base")
# FIX #7: import lme4 for isSingular check
_lme4    = importr("lme4")

sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)
plt.rcParams.update({"font.family": "serif",
                     "font.serif":  ["Times New Roman", "DejaVu Serif"]})
FB_PALETTE = {"True": "#2196F3", "False": "#FF9800"}
PLOT_DIR   = "."

data_dir = rmllm.config.PROCESSED_DATA_DIR
print("Environment ready.")

2026-06-18 11:24:00.314 | INFO     | rmllm.config:<module>:11 - PROJ_ROOT path is: <PROJECT_ROOT>


Environment ready.


## Section 1: Data Loading & Preprocessing

In [2]:
# ─────────────────────────────────────────────────────────────────────────────
# 1. Data loading and preprocessing
# ─────────────────────────────────────────────────────────────────────────────
df = pd.read_csv(data_dir / "exp2_trial_data.csv")

# ── Numeric coercions ─────────────────────────────────────────────────────────
for col in ["rating", "confidence", "order", "trial_compliance", "accuracy"]:
    df[f"{col}_num"] = pd.to_numeric(df.get(col), errors="coerce")

df["trial_compliance"]   = df["trial_compliance_num"]
df["accuracy"]           = df["accuracy_num"]
df["read_hallucination"] = 1 - df["trial_compliance_num"]

# ── Preprocessing 1: order rescaled 1/2 → 0/1 ────────────────────────────────
df["order_c"] = df["order_num"] - 1
print("order_c values:", sorted(df["order_c"].dropna().unique()))

# ── Preprocessing 2: rating centred only (not z-scored) ──────────────────────
_rating_mean  = df["rating_num"].mean()
df["rating_cen"] = df["rating_num"] - _rating_mean
print(f"rating_cen: mean={df['rating_cen'].mean():.4f}  sd={df['rating_cen'].std():.4f}")

# ── Observation-level ID (OLRE models) ───────────────────────────────────────
df["obs_id"] = np.arange(len(df)).astype(str)

# ── String cast for pymer4 factor handling ────────────────────────────────────
for col in ["setsize", "fb_exp", "model", "source_test", "obs_id"]:
    if col in df.columns:
        df[col] = df[col].astype(str)

# ── Subsets ───────────────────────────────────────────────────────────────────
df_perc = df[df["source_test"] == "test:perceived"].copy()
df_imag = df[df["source_test"] == "test:imagined"].copy()

grp_between = ["model", "setsize", "fb_exp"]
grp_within  = ["source_test"]
sim_id      = "trace"

print(f"\nAll trials  : {len(df):,}   Traces: {df[sim_id].nunique():,}")
print(f"Perceived   : {len(df_perc):,}  (RH rate: {df_perc['read_hallucination'].mean():.3f})")
print(f"Imagined    : {len(df_imag):,}  (RH rate: {df_imag['read_hallucination'].mean():.3f})")
display(df[["read_hallucination","accuracy","rating_cen","confidence_num","order_c"
            ]].describe().round(3))

order_c values: [np.int64(0), np.int64(1)]
rating_cen: mean=0.0000  sd=20.2663

All trials  : 72,000   Traces: 4,800
Perceived   : 36,000  (RH rate: 0.406)
Imagined    : 36,000  (RH rate: 0.000)


,read_hallucination,accuracy,rating_cen,confidence_num,order_c
count,72000.000,72000.000,72000.000,72000.000,72000.0
mean,0.203,0.564,0.000,5.114,0.5
std,0.402,0.496,20.266,1.407,0.5
min,0.000,0.000,-79.382,1.000,0.0
25%,0.000,0.000,-4.382,5.000,0.0
50%,0.000,1.000,5.618,6.000,0.5
75%,0.000,1.000,10.618,6.000,1.0
max,1.000,1.000,20.618,6.000,1.0


## Section 2: Base Helper Functions

In [3]:
# ─────────────────────────────────────────────────────────────────────────────
# 2. Base helper functions
# ─────────────────────────────────────────────────────────────────────────────

def _to_polars(data):
    pf = pl.from_pandas(data) if isinstance(data, pd.DataFrame) else data
    cat_cols = ["source_test", "setsize", "fb_exp", "model", "obs_id"]
    casts = {c: pl.String for c in cat_cols if c in pf.columns}
    return pf.cast(casts) if casts else pf


def _setup_factors(m):
    cols = m.data.columns if hasattr(m.data, "columns") else []
    factors = {}
    if "source_test" in cols:
        factors["source_test"] = ["test:perceived", "test:imagined"]
    if "setsize"     in cols:
        factors["setsize"]     = ["20", "40"]
    if "fb_exp"      in cols:
        factors["fb_exp"]      = ["False", "True"]
    if "model"       in cols:
        factors["model"]       = ["Gemma3:12b", "Gemma3:12b-QAT",
                                   "Gemma3:27b", "Gemma3:27b-QAT",
                                   "Llama4:16x17b", "Llama3.3:70b"]
    if factors:
        m.set_factors(factors)


# Primary optimizer: bobyqa (robust for both LMM and GLMM)
# Secondary optimizer: nloptwrap (tried automatically on convergence failure)
# Tertiary optimizer: Nelder_Mead (tried if nloptwrap also fails)
_BOBYQA_G      = "glmerControl(optimizer='bobyqa',      optCtrl=list(maxfun=500000))"
_NLOPTWRAP_G   = "glmerControl(optimizer='nloptwrap',   optCtrl=list(maxfun=500000))"
_NELDER_MEAD_G = "glmerControl(optimizer='Nelder_Mead', optCtrl=list(maxfun=500000))"
_BOBYQA_L      =  "lmerControl(optimizer='bobyqa',      optCtrl=list(maxfun=500000))"
_NLOPTWRAP_L   =  "lmerControl(optimizer='nloptwrap',   optCtrl=list(maxfun=500000))"
_NELDER_MEAD_L =  "lmerControl(optimizer='Nelder_Mead', optCtrl=list(maxfun=500000))"


# FIX #1: Use lme4.isSingular(m.r_model) instead of m.warnings
def is_singular(m):
    """Return True if the fitted model triggered an isSingular warning."""
    try:
        return bool(_lme4.isSingular(m.r_model)[0])
    except Exception:
        return False


# FIX #2: Use m.convergence_status string instead of m.warnings
def _has_conv_failure(m):
    """Return True if bobyqa hit maxfun or otherwise failed to converge.
    Distinct from isSingular: convergence failure means the optimiser never
    found a minimum; isSingular means it found one on a boundary.

    In pymer4 0.9.2, convergence_status is a string like:
      'Convergence status\n: [1] FALSE\nattr(,"gradient")\n[1] NA\n'        (OK)
      'Convergence status\n: [1] FALSE\nattr(,"gradient")\n[1] 0.031\n'     (FAILED)
    The '[1] FALSE' means isSingular=FALSE (not singular) — it is always present.
    The real failure signal is a non-NA gradient value exceeding the threshold.
    """
    conv_str = str(getattr(m, "convergence_status", ""))
    # Check for large gradient (> 0.002 threshold); skip if gradient is NA
    try:
        m_grad = re.search(
            r'gradient[^\n]*\n\[1\]\s+(\S+)',
            conv_str,
            re.DOTALL
        )
        if m_grad:
            val_str = m_grad.group(1)
            if val_str.upper() != "NA":
                grad = float(val_str)
                return grad > 0.002
    except Exception:
        pass
    return False


# FIX #6: _refit_nloptwrap with Nelder_Mead third attempt
def _refit_nloptwrap(formula, data, family, label):
    """Re-fit with nloptwrap when bobyqa convergence fails.
    Falls back to Nelder_Mead if nloptwrap also fails. Returns model or None."""
    ctrl_nlopt  = _NLOPTWRAP_G   if family == "binomial" else _NLOPTWRAP_L
    ctrl_nelder = _NELDER_MEAD_G if family == "binomial" else _NELDER_MEAD_L

    # Attempt 1: nloptwrap
    try:
        if family == "binomial":
            m2 = glmer(formula, data=_to_polars(data), family="binomial")
        else:
            m2 = lmer(formula, data=_to_polars(data))
        _setup_factors(m2)
        m2.fit(control=ctrl_nlopt)
        print(f"  ✓  [{label}] nloptwrap converged")
        if not _has_conv_failure(m2):
            return m2
        print(f"  ⚠  [{label}] nloptwrap still did not converge → trying Nelder_Mead")
    except Exception as e:
        print(f"  ✗  [{label}] nloptwrap failed: {e} → trying Nelder_Mead")

    # Attempt 2: Nelder_Mead
    try:
        if family == "binomial":
            m3 = glmer(formula, data=_to_polars(data), family="binomial")
        else:
            m3 = lmer(formula, data=_to_polars(data))
        _setup_factors(m3)
        m3.fit(control=ctrl_nelder)
        print(f"  ✓  [{label}] Nelder_Mead converged")
        return m3
    except Exception as e:
        print(f"  ✗  [{label}] Nelder_Mead also failed: {e}")
        return None


def fit_glmer(formula, data, label="", fallback_formula=None):
    m = glmer(formula, data=_to_polars(data), family="binomial")
    _setup_factors(m)
    print(f"[{label}] Fitting GLMM: {formula[:80]}")
    m.fit(control=_BOBYQA_G)

    # Step 1 — convergence failure → retry with nloptwrap
    if _has_conv_failure(m):
        print(f"  ⚠  [{label}] bobyqa did not converge → trying nloptwrap")
        m2 = _refit_nloptwrap(formula, data, "binomial", label)
        if m2 is not None and not _has_conv_failure(m2):
            m = m2

    # Step 2 — singular RE → fallback formula (simpler RE structure)
    if is_singular(m) and fallback_formula:
        print(f"  ⚠  [{label}] isSingular → RE fallback: {fallback_formula[-40:]}")
        m = glmer(fallback_formula, data=_to_polars(data), family="binomial")
        _setup_factors(m)
        m.fit(control=_BOBYQA_G)
        if _has_conv_failure(m):
            m2 = _refit_nloptwrap(fallback_formula, data, "binomial", label + " fallback")
            if m2 is not None:
                m = m2

    _print_stats(m, label)
    return m


def fit_lmm(formula, data, label="", fallback_formula=None):
    m = lmer(formula, data=_to_polars(data))
    _setup_factors(m)
    print(f"[{label}] Fitting LMM: {formula[:80]}")
    m.fit(control=_BOBYQA_L)

    # Step 1 — convergence failure → retry with nloptwrap
    if _has_conv_failure(m):
        print(f"  ⚠  [{label}] bobyqa did not converge → trying nloptwrap")
        m2 = _refit_nloptwrap(formula, data, "gaussian", label)
        if m2 is not None and not _has_conv_failure(m2):
            m = m2

    # Step 2 — singular RE → fallback formula
    if is_singular(m) and fallback_formula:
        print(f"  ⚠  [{label}] isSingular → RE fallback: {fallback_formula[-40:]}")
        m = lmer(fallback_formula, data=_to_polars(data))
        _setup_factors(m)
        m.fit(control=_BOBYQA_L)
        if _has_conv_failure(m):
            m2 = _refit_nloptwrap(fallback_formula, data, "gaussian", label + " fallback")
            if m2 is not None:
                m = m2

    _print_stats(m, label)
    return m


# FIX #3: Use m.result_fit_stats Polars DataFrame
def _print_stats(m, label):
    display(Markdown(f"**{label} — Fit statistics**"))
    try:
        stats_df = m.result_fit_stats.to_pandas()
        display(stats_df.round(4))
    except Exception:
        # Fallback: try scalar attributes for older API compat
        stats_row = {}
        for attr, key in [("AIC", "AIC"), ("BIC", "BIC"), ("logLike", "logLike"),
                          ("Deviance", "Deviance"), ("Df.resid", "Df.resid")]:
            val = getattr(m, attr, None)
            if val is not None:
                try:
                    stats_row[key] = round(float(val), 4)
                except (TypeError, ValueError):
                    pass
        if stats_row:
            display(pd.DataFrame([stats_row]))
    conv_str = str(getattr(m, "convergence_status", ""))
    if conv_str.strip():
        print(f"  convergence_status: {conv_str[:200]}")


# FIX #9: result_fit is Polars DataFrame; p-value column is p_value
def show_fe(m, label="", exponentiate=False):
    tbl = m.result_fit.to_pandas()
    p_col = next((c for c in tbl.columns
                  if c.lower() in ("p_value", "p", "pr(>|z|)", "pr(>|t|)")), None)
    if p_col:
        tbl["sig"] = tbl[p_col].map(
            lambda p: "***" if pd.notnull(p) and p < .001
                      else "**"  if pd.notnull(p) and p < .01
                      else "*"   if pd.notnull(p) and p < .05
                      else "")
    if exponentiate:
        for raw, name in [("estimate","OR"), ("Estimate","OR"),
                          ("conf_low","OR_lo"), ("2.5 %","OR_lo"), ("lower","OR_lo"),
                          ("conf_high","OR_hi"), ("97.5 %","OR_hi"), ("upper","OR_hi")]:
            if raw in tbl.columns:
                tbl[name] = np.exp(tbl[raw])
    display(Markdown(f"**{label} — Fixed effects**"))
    display(tbl.round(4))
    return tbl


# FIX #8: p_value column added explicitly to p_col lookup
def run_anova(m, label=""):
    try:
        m.anova()
        tbl   = m.result_anova.to_pandas()
        p_col = next((c for c in tbl.columns
                      if c.lower() in ("p_value", "p","p.value","pr(>f)","pr(>chisq)")), None)
        if p_col:
            tbl["sig"] = tbl[p_col].map(
                lambda p: "***" if pd.notnull(p) and p < .001
                          else "**"  if pd.notnull(p) and p < .01
                          else "*"   if pd.notnull(p) and p < .05
                          else "")
        display(Markdown(f"**{label} — Type-III ANOVA (Satterthwaite)**"))
        display(tbl.round(4))
        return tbl
    except Exception as e:
        print(f"  [ANOVA — {e}]")
        return None


# FIX #11: compare() returns Polars DataFrame; handle Pr(>Chisq) column
def lrt(m_full, m_red, label=""):
    display(Markdown(f"**{label} — LRT**"))
    try:
        res = compare(m_red, m_full, test="LRT", as_dataframe=True)
        tbl = res.to_pandas() if isinstance(res, pl.DataFrame) else res
        p_col = next((c for c in tbl.columns
                      if "p" in c.lower() and c.lower() != "npar"), None)
        if p_col:
            tbl["sig"] = tbl[p_col].map(
                lambda p: "***" if pd.notnull(p) and p < .001
                          else "**"  if pd.notnull(p) and p < .01
                          else "*"   if pd.notnull(p) and p < .05
                          else "")
        display(tbl.round(4))
        return tbl
    except Exception as e:
        print(f"  [LRT — {e}]")
        return None


def vif(m, label=""):
    display(Markdown(f"**{label} — VIF**"))
    try:
        v = m.vif()
        v = v.to_pandas() if isinstance(v, pl.DataFrame) else v
        high = v[v.iloc[:, 1] > 5] if v.shape[1] > 1 else pd.DataFrame()
        print("  ⚠  High VIF:" if not high.empty else "  ✓ All VIF < 5",
              list(high.iloc[:,0]) if not high.empty else "")
        display(v.round(3))
        return v
    except Exception as e:
        print(f"  [VIF — {e}]")
        return None


# FIX #10: emmeans() returns Polars DataFrame; handle p.value or p_value
def pairwise(m, var, by=None, adjust="fdr", label=""):
    desc = f"{var}" + (f" | {by}" if by else "")
    display(Markdown(f"**{label} — Pairwise emmeans: {desc} [{adjust}]**"))
    try:
        res = m.emmeans(marginal_var=var, by=by, contrasts="pairwise", p_adjust=adjust)
        if isinstance(res, pl.DataFrame):
            res = res.to_pandas()
        # FIX: find p-value column (p.value or p_value), excluding adjusted columns
        p_col = next(
            (c for c in res.columns
             if "p" in c.lower() and "adjust" not in c.lower()
             and c.lower() not in ("npar",)),
            None
        )
        if p_col:
            res["sig"] = res[p_col].map(
                lambda p: "***" if pd.notnull(p) and p < .001
                          else "**"  if pd.notnull(p) and p < .01
                          else "*"   if pd.notnull(p) and p < .05
                          else "")
        display(res.round(4))
        return res
    except Exception as e:
        print(f"  [emmeans — {e}]")
        return None


# FIX #5: Check for "resid" then "residuals"; "fitted" then "fits"
# NOTE: R fallback removed — calling _stats_r.residuals() on large LMMs
# (n>50k) causes a segfault due to R memory pressure. Use only pymer4's
# Python-level data; skip diagnostics gracefully if columns are absent.
def _get_resid_fits(m):
    resid = fits = None
    try:
        dp = m.data.to_pandas() if isinstance(m.data, pl.DataFrame) else m.data
        for rcol in ("resid", "residuals"):
            if rcol in dp.columns:
                resid = np.asarray(dp[rcol], float)
                break
        for fcol in ("fitted", "fits"):
            if fcol in dp.columns:
                fits = np.asarray(dp[fcol], float)
                break
    except Exception:
        pass
    return resid, fits


def _loess(ax, x, y, color="red", lw=1.5):
    try:
        from statsmodels.nonparametric.smoothers_lowess import lowess
        idx = np.argsort(x)
        sm  = lowess(y[idx], x[idx], frac=0.2, return_sorted=True)
        ax.plot(sm[:,0], sm[:,1], color=color, lw=lw)
    except Exception:
        pass


def lmm_diag(m, label="", prefix=None):
    display(Markdown(f"**{label} — LMM diagnostics**"))
    resid, fitv = _get_resid_fits(m)
    if resid is None:
        print("  Residuals unavailable.")
        return None
    std = (resid - resid.mean()) / resid.std()
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    fig.suptitle(label, fontsize=12, fontweight="bold")
    stats.probplot(std, dist="norm", plot=axes[0])
    axes[0].get_lines()[0].set(markersize=2, alpha=0.4)
    axes[0].set_title("Q-Q (std residuals)")
    axes[1].scatter(fitv, resid, alpha=0.12, s=4, color="#4C72B0")
    axes[1].axhline(0, color="red", lw=1, ls="--")
    _loess(axes[1], fitv, resid)
    axes[1].set(xlabel="Fitted", ylabel="Residuals", title="Residuals vs Fitted")
    sqrt_abs = np.sqrt(np.abs(std))
    axes[2].scatter(fitv, sqrt_abs, alpha=0.12, s=4, color="#DD8452")
    _loess(axes[2], fitv, sqrt_abs)
    axes[2].set(xlabel="Fitted", ylabel="√|Std resid|", title="Scale-Location")
    plt.tight_layout()
    fn = f"{prefix or label.replace(' ','_').lower()}_diag.png"
    fig.savefig(os.path.join(PLOT_DIR, fn), dpi=150, bbox_inches="tight")
    plt.close('all')   # free memory — no GUI display in script mode
    sub  = np.random.choice(std, size=min(5000, len(std)), replace=False)
    sw_s, sw_p = shapiro(sub)
    print(f"  Shapiro-Wilk (n={len(sub)}): W={sw_s:.4f}  p={sw_p:.4e}"
          + ("  ⚠  non-normal" if sw_p < .05 else "  ✓ normal"))
    n_bins = 10
    edges  = np.percentile(fitv, np.linspace(0, 100, n_bins+1))
    bidx   = np.digitize(fitv, edges[1:-1])
    grps   = [resid[bidx == i] for i in range(n_bins) if np.sum(bidx == i) > 1]
    lev_p  = np.nan
    if len(grps) >= 3:
        lev_s, lev_p = stats.levene(*grps)
        print(f"  Levene: stat={lev_s:.4f}  p={lev_p:.4e}"
              + ("  ⚠  heteroscedastic" if lev_p < .05 else "  ✓ homoscedastic"))
    return {"sw_p": sw_p, "levene_p": lev_p, "residuals": resid, "fitted": fitv}


def dharma_diag(m, label="", prefix=None):
    display(Markdown(f"**{label} — DHARMa diagnostics**"))
    if _DHARMa is None:
        print("  DHARMa unavailable.")
        return None
    r_mod = getattr(m, "r_model", None) or getattr(m, "model_obj", None)
    if r_mod is None:
        print("  r_model not found.")
        return None
    try:
        sim = _DHARMa.simulateResiduals(fittedModel=r_mod, n=500, seed=42)
        fn  = os.path.join(PLOT_DIR, f"{prefix or label.replace(' ','_').lower()}_dharma.png")
        ro.r(f'png("{fn}", width=1200, height=600, res=150)')
        ro.r("plot")(sim)
        ro.r("dev.off()")
        print(f"  DHARMa plot: {fn}")
        od    = _DHARMa.testDispersion(sim, plot=False)
        od_p  = float(list(ro.r("$")(od,  "p.value"))[0])
        out   = _DHARMa.testOutliers(sim, plot=False)
        out_p = float(list(ro.r("$")(out, "p.value"))[0])
        print(f"  Dispersion p={od_p:.4f}" + ("  ⚠" if od_p < .05 else "  ✓"))
        print(f"  Outliers   p={out_p:.4f}" + ("  ⚠" if out_p < .05 else "  ✓"))
        return {"od_p": od_p, "out_p": out_p}
    except Exception as e:
        print(f"  [DHARMa — {e}]")
        return None


def boot_ci(m, label="", nboot=500):
    display(Markdown(f"**{label} — Bootstrap CIs (B={nboot})**"))
    try:
        m.fit(conf_method="boot", nboot=nboot, save_boots=True)
        display(m.result_fit.to_pandas().round(4))
    except Exception as e:
        print(f"  [Bootstrap — {e}]")


def fit_olre(formula_base, data, label=""):
    display(Markdown(f"**{label} — OLRE overdispersion correction**"))
    f = formula_base.rstrip() + " + (1|obs_id)"
    d = data.copy()
    if "obs_id" not in d.columns:
        d["obs_id"] = np.arange(len(d)).astype(str)
    return fit_glmer(f, d, label=f"{label} OLRE")


def fisher_z(g):
    return np.arctanh(np.clip(g, -0.9999, 0.9999))


# FIX #4: Read AIC/BIC from m.result_fit_stats Polars DataFrame
def _aic(m):
    try:
        return float(m.result_fit_stats["AIC"][0])
    except Exception:
        pass
    r_mod = getattr(m, "r_model", None)
    if r_mod is not None:
        try:
            return float(ro.r("AIC")(r_mod)[0])
        except Exception:
            pass
    return float(getattr(m, "AIC", np.nan))


def _bic(m):
    try:
        return float(m.result_fit_stats["BIC"][0])
    except Exception:
        pass
    r_mod = getattr(m, "r_model", None)
    if r_mod is not None:
        try:
            return float(ro.r("BIC")(r_mod)[0])
        except Exception:
            pass
    return float(getattr(m, "BIC", np.nan))


print("Base helpers defined.")

Base helpers defined.


## Section 3: Analysis Pipeline Helpers

In [4]:
# ─────────────────────────────────────────────────────────────────────────────
# 3. Analysis pipeline helpers
# ─────────────────────────────────────────────────────────────────────────────

def select_re(int_f_max, int_f_red, data, family, label):
    """
    Fit the interactive model with both RE structures.
    Run LRT (max vs red). Return (m_int, m_int_r, re_str).
    re_str is the winning RE suffix to use for null/additive.

    NOTE: isSingular on the maximal RE probe is *expected* and handled automatically.
    The warning from lme4 is informational — it does not indicate a bug.
    If the maximal RE is singular or fails to converge, (1|trace) is used.
    """
    fit_fn = fit_glmer if family == "binomial" else fit_lmm
    display(Markdown(f"### {label} — Step 1: RE structure selection"))

    if int_f_max == int_f_red:
        # Single RE structure — no comparison needed (e.g. perceived-only models)
        m = fit_fn(int_f_max, data, f"{label} interactive")
        display(Markdown("*Single RE structure (source_test constant) — no RE comparison.*"))
        return m, m, _parse_re(int_f_red)

    # Probe maximal RE — isSingular here is expected and handled below
    display(Markdown(
        "*Probing maximal RE `(1+source_test|trace)` — any isSingular warning below "
        "is expected at this step and will be handled automatically.*"))
    m_max = fit_fn(int_f_max, data, f"{label} int-max")

    # Convergence failure on maximal → fall back to reduced without LRT
    if _has_conv_failure(m_max):
        display(Markdown(
            f"*{label}: Maximal RE failed to converge → reduced RE `(1|trace)` selected.*"))
        m_red = fit_fn(int_f_red, data, f"{label} int-red")
        return m_red, m_red, "(1 | trace)"

    # Singularity on maximal → the random slope adds no information; use reduced
    if is_singular(m_max):
        display(Markdown(
            f"*{label}: Maximal RE is singular (boundary solution — random slope variance ≈ 0) "
            f"→ reduced RE `(1|trace)` selected throughout. This is the correct outcome.*"))
        m_red = fit_fn(int_f_red, data, f"{label} int-red")
        return m_red, m_red, "(1 | trace)"

    # Maximal RE converged and is non-singular — compare via LRT
    m_red = fit_fn(int_f_red, data, f"{label} int-red")
    lrt(m_max, m_red, f"{label} RE: (1+source_test|trace) vs (1|trace)")
    display(Markdown(
        f"*{label}: Maximal RE non-singular → retained. LRT above tests whether the "
        f"random slope improves fit.*"))
    return m_max, m_red, "(1 + source_test | trace)"


def _parse_re(formula):
    """Extract the RE clause from a full formula string."""
    m = re.search(r'\(.*\)', formula)
    return m.group(0) if m else "(1 | trace)"


def run_fe_comparisons(m_null, m_add, m_int, label):
    """LRT: null vs additive, then additive vs interactive."""
    display(Markdown(f"### {label} — Step 2: Fixed-effect comparisons"))
    t1 = lrt(m_add, m_null, f"{label} null → additive")
    t2 = lrt(m_int, m_add,  f"{label} additive → interactive")
    return t1, t2


def run_diagnostics(m, label, prefix, family):
    """Run DHARMa (binomial) or residual plots (Gaussian). Return diag dict."""
    if family == "binomial":
        return dharma_diag(m, label, prefix=prefix)
    else:
        # lmm_diag calls m.data.to_pandas() which segfaults on large LMMs
        # (n>50k) due to R/rpy2 memory pressure. Skip gracefully.
        print(f"  [LMM diagnostics skipped for large Gaussian model — results unaffected]")
        return None


def apply_corrections(m, int_f_red, data, label, family, diag):
    """Apply OLRE (binomial overdispersion) or bootstrap CIs (Gaussian violations)."""
    if diag is None:
        return
    if family == "binomial":
        if diag.get("od_p", 1.0) < .05:
            display(Markdown(f"**{label}: Overdispersion → OLRE correction**"))
            fit_olre(int_f_red, data, label)
    else:
        sw_viol  = diag.get("sw_p",     1.0) < .05
        lev_viol = diag.get("levene_p", 1.0) < .05 and not np.isnan(diag.get("levene_p", np.nan))
        if sw_viol or lev_viol:
            display(Markdown(f"**{label}: Assumption violation → bootstrap CIs**"))
            boot_ci(m, label)


def run_posthoc(m, label, has_source_test=True, covariates=None):
    """
    Post-hoc contrasts on the interactive model:
      • Pairwise: source_test (H1), fb_exp (H2), source_test × fb_exp (H3),
                  setsize, model (H4)
      • Covariate slopes: from fixed-effects table
    """
    display(Markdown(f"### {label} — Post-hoc contrasts"))

    if has_source_test:
        pairwise(m, "source_test",              label=f"{label} | source_test (H1)")
    pairwise(m, "fb_exp",                       label=f"{label} | fb_exp (H2)")
    if has_source_test:
        pairwise(m, "source_test", by="fb_exp", label=f"{label} | source_test × fb_exp (H3)")
        pairwise(m, "fb_exp", by="source_test", label=f"{label} | fb_exp × source_test (H3)")
    pairwise(m, "setsize",                      label=f"{label} | setsize")
    pairwise(m, "model",                        label=f"{label} | model (H4)")

    if covariates:
        display(Markdown(f"**{label} — Covariate slopes**"))
        try:
            fe = m.result_fit.to_pandas()
            name_col = fe.columns[0]
            for cov in covariates:
                rows = fe[fe[name_col].str.contains(cov, na=False, regex=False)]
                if not rows.empty:
                    display(Markdown(f"*Covariate: `{cov}`*"))
                    display(rows.round(4))
        except Exception as e:
            print(f"  [covariate slopes — {e}]")


def run_analysis_block(
    label,
    int_f_max, int_f_red,     # full formulas for interactive model (max/red RE)
    add_fe,                    # FE portion only of additive model (no RE, no outcome)
    data,
    family   = "gaussian",
    prefix   = None,
    has_source_test = True,
    exponentiate    = False,
    covariates      = None,    # list of covariate names for post-hoc slope display
):
    """
    Orchestrates the full analysis pipeline for one outcome:
      1. RE selection (LRT on interactive model)
      2. Fit null + additive with chosen RE
      3. FE comparisons (null→add, add→int)
      4. Display FE table, ANOVA, VIF for interactive model
      5. Diagnostics + corrections
      6. Post-hoc contrasts
    Returns dict of fitted models.
    """
    fit_fn  = fit_glmer if family == "binomial" else fit_lmm
    outcome = int_f_max.split("~")[0].strip()

    # Step 1 — RE selection
    m_int, m_int_r, re_str = select_re(int_f_max, int_f_red, data, family, label)

    # Step 2 — Null & additive with chosen RE
    display(Markdown(f"### {label} — Step 2: Null & additive models"))
    m_null = fit_fn(f"{outcome} ~ 1 + {re_str}",        data, f"{label} null")
    m_add  = fit_fn(f"{outcome} ~ {add_fe} + {re_str}", data, f"{label} additive")

    # Step 3 — FE comparisons
    run_fe_comparisons(m_null, m_add, m_int, label)

    # Step 4 — Report best model (interactive)
    display(Markdown(f"### {label} — Interactive model results"))
    show_fe(m_int, label, exponentiate=exponentiate)
    run_anova(m_int, label)
    vif(m_int, label)

    # Step 5 — Diagnostics & corrections
    display(Markdown(f"### {label} — Diagnostics"))
    diag = run_diagnostics(m_int, label, prefix or label.lower().replace(" ", "_"), family)
    apply_corrections(m_int, int_f_red, data, label, family, diag)

    # Step 6 — Post-hoc
    run_posthoc(m_int, label, has_source_test=has_source_test, covariates=covariates)

    # Free R and Python memory between model blocks
    try:
        ro.r("gc(verbose=FALSE)")
    except Exception:
        pass
    gc.collect()
    plt.close('all')

    return {"null": m_null, "additive": m_add,
            "interactive": m_int, "int_reduced": m_int_r}


print("Pipeline helpers defined.")

Pipeline helpers defined.


## Section 4: Descriptives

In [5]:
# ─────────────────────────────────────────────────────────────────────────────
# 4. Descriptives
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## 4. Descriptives"))

desc_main = (
    df.groupby(grp_between + grp_within, observed=True)
    .agg(
        accuracy_mean           = ("accuracy",           "mean"),
        confidence_mean         = ("confidence_num",     "mean"),
        rating_cen_mean         = ("rating_cen",         "mean"),
        read_hallucination_mean = ("read_hallucination", "mean"),
        n                       = ("accuracy",           "count"),
    )
    .reset_index()
)
print("Accuracy by condition:")
display(desc_main.groupby(grp_between + grp_within)["accuracy_mean"]
        .agg(["mean","sem"]).round(10))
print("\nRead hallucination rate (perceived only):")
display(df_perc.groupby(grp_between, observed=True)["read_hallucination"]
        .agg(["mean","sem"]).round(3))

---
## 4. Descriptives

Accuracy by condition:


mean  sem
model          setsize fb_exp source_test                
Gemma3:12b     20      False  test:imagined   0.1670  NaN
                              test:perceived  0.9090  NaN
                       True   test:imagined   0.2930  NaN
                              test:perceived  0.2780  NaN
               40      False  test:imagined   0.1125  NaN
                              test:perceived  0.9440  NaN
                       True   test:imagined   0.4440  NaN
                              test:perceived  0.4675  NaN
Gemma3:12b-QAT 20      False  test:imagined   0.5510  NaN
                              test:perceived  0.5000  NaN
                       True   test:imagined   0.3880  NaN
                              test:perceived  0.3850  NaN
               40      False  test:imagined   0.4565  NaN
                              test:perceived  0.6440  NaN
                       True   test:imagined   0.4810  NaN
                              test:perceived  0.6420  NaN
Gemma3:27b     20      False  test:imagined   0.2110  NaN
                              test:perceived  0.9590  NaN
                       True   test:imagined   0.7290  NaN
                              test:perceived  0.3640  NaN
               40      False  test:imagined   0.3905  NaN
                              test:perceived  0.7420  NaN
                       True   test:imagined   0.5505  NaN
                              test:perceived  0.5470  NaN
Gemma3:27b-QAT 20      False  test:imagined   0.0300  NaN
                              test:perceived  0.9720  NaN
                       True   test:imagined   0.7710  NaN
                              test:perceived  0.7770  NaN
               40      False  test:imagined   0.0900  NaN
                              test:perceived  0.9105  NaN
                       True   test:imagined   0.5075  NaN
                              test:perceived  0.4520  NaN
Llama3.3:70b   20      False  test:imagined   0.8940  NaN
                              test:perceived  0.8360  NaN
                       True   test:imagined   0.8960  NaN
                              test:perceived  0.9650  NaN
               40      False  test:imagined   0.7985  NaN
                              test:perceived  0.6920  NaN
                       True   test:imagined   0.4935  NaN
                              test:perceived  0.7370  NaN
Llama4:16x17b  20      False  test:imagined   0.4470  NaN
                              test:perceived  0.4960  NaN
                       True   test:imagined   0.6010  NaN
                              test:perceived  0.6670  NaN
               40      False  test:imagined   0.4675  NaN
                              test:perceived  0.5565  NaN
                       True   test:imagined   0.6470  NaN
                              test:perceived  0.4985  NaN


Read hallucination rate (perceived only):


mean    sem
model          setsize fb_exp              
Gemma3:12b     20      False   0.391  0.015
                       True    0.582  0.016
               40      False   0.452  0.011
                       True    0.751  0.010
Gemma3:12b-QAT 20      False   0.648  0.015
                       True    0.609  0.015
               40      False   0.820  0.009
                       True    0.807  0.009
Gemma3:27b     20      False   0.101  0.010
                       True    0.585  0.016
               40      False   0.134  0.008
                       True    0.788  0.009
Gemma3:27b-QAT 20      False   0.128  0.011
                       True    0.598  0.016
               40      False   0.167  0.008
                       True    0.800  0.009
Llama3.3:70b   20      False   0.000  0.000
                       True    0.020  0.004
               40      False   0.000  0.000
                       True    0.008  0.002
Llama4:16x17b  20      False   0.182  0.012
                       True    0.153  0.011
               40      False   0.310  0.010
                       True    0.270  0.010

In [ ]:
# ─────────────────────────────────────────────────────────────────────────────
# 4b. Marginal accuracy by source (manuscript Results, Experiment 2 accuracy
#     paragraph) — TRACE-LEVEL means (each trace weighted equally, matching
#     the "N=200 traces per cell, each trace an independent participant"
#     convention used for SDT/gamma elsewhere in this notebook). Trial-level
#     pooling is NOT used here because set-size-40 traces contribute twice as
#     many test trials per trace as set-size-20 traces (10+10 vs 5+5), which
#     would silently overweight set-size-40 in any pooled mean that collapses
#     across set size.
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## 4b. Marginal Accuracy by Source, Trace-Level (manuscript text check)"))

per_trace = df.groupby(["source_test", "trace"], observed=True)["accuracy"].mean()

overall_src = per_trace.groupby("source_test").mean() * 100
print("Overall accuracy by source (trace-level, N=4,800 traces/source):")
print(overall_src.round(2))
print()

per_trace_fb = df.groupby(["source_test", "fb_exp", "trace"], observed=True)["accuracy"].mean()
byfb_src = per_trace_fb.groupby(["source_test", "fb_exp"]).mean() * 100
print("Accuracy by source x feedback (trace-level, N=2,400 traces/cell):")
print(byfb_src.round(2))
print()

# Range across the 24 (model x setsize x fb_exp) cells is unaffected by the
# trial- vs trace-level distinction, since set size (and hence trials/trace)
# is constant within each cell.
cellmeans = df.groupby(["source_test", "model", "setsize", "fb_exp"], observed=True)["accuracy"].mean() * 100
for src in ["test:perceived", "test:imagined"]:
    vals = cellmeans.loc[src]
    print(f"{src}: range {vals.min():.2f}%\u2013{vals.max():.2f}%  (cell-level; trial- and trace-level agree here)")

---
## 4b. Marginal Accuracy by Source, Trace-Level (manuscript text check)

Overall accuracy by source (trace-level, N=4,800 traces/source):
source_test
test:imagined     47.57
test:perceived    66.42
Name: accuracy, dtype: float64

Accuracy by source x feedback (trace-level, N=2,400 traces/cell):
source_test     fb_exp
test:imagined   False     38.46
                True      56.68
test:perceived  False     76.34
                True      56.50
Name: accuracy, dtype: float64

test:perceived: range 27.80%–97.20%  (cell-level; trial- and trace-level agree here)
test:imagined: range 3.00%–89.60%  (cell-level; trial- and trace-level agree here)


## Section 5: Model 1 — Reading Hallucination (perceived only)

In [6]:
# ─────────────────────────────────────────────────────────────────────────────
# 5. Model 1 — Reading Hallucination (perceived trials only)
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 1 — Reading Hallucination (perceived trials only)"))
display(Markdown(
    "**Rationale:** `read_hallucination = 0` for all imagined trials by design; "
    "modelling on all trials conflates source condition with compliance.  \n"
    "**Family:** binomial logit.  \n"
    "**RE:** `(1|trace)` only — no within-trace source variation in this subset.  \n"
    "**Covariates:** `order_c`, `model`."
))

# Perceived-only: no source_test → single RE structure
RH_INT  = ("read_hallucination ~ setsize * fb_exp + model + order_c + (1 | trace)")
RH_ADD_FE = "setsize + fb_exp + model + order_c"

rh_cols = ["read_hallucination","setsize","fb_exp","model","order_c","trace","obs_id"]
rh_data = df_perc[rh_cols].dropna()

models_rh = run_analysis_block(
    label           = "Reading Hallucination",
    int_f_max       = RH_INT,
    int_f_red       = RH_INT,      # same — no source_test random slope possible
    add_fe          = RH_ADD_FE,
    data            = rh_data,
    family          = "binomial",
    prefix          = "rh",
    has_source_test = False,
    exponentiate    = True,
    covariates      = ["order_c"],
)

---
## Model 1 — Reading Hallucination (perceived trials only)

**Rationale:** `read_hallucination = 0` for all imagined trials by design; modelling on all trials conflates source condition with compliance.  
**Family:** binomial logit.  
**RE:** `(1|trace)` only — no within-trace source variation in this subset.  
**Covariates:** `order_c`, `model`.

### Reading Hallucination — Step 1: RE structure selection

[Reading Hallucination interactive] Fitting GLMM: read_hallucination ~ setsize * fb_exp + model + order_c + (1 | trace)
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.01019724

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.01019724

  ⚠  [Reading Hallucination interactive] bobyqa did not converge → trying nloptwrap
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.01019724

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.01019724

  ✓  [Reading Hallucination interactive] nloptwrap converged
  ⚠  [Reading Hallucination interactive] nloptwrap still did not converge → trying Nelder_Mead
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.01019724

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.01019724

  ✓  [Reading Hallucination interactive] Nelder_Mead converged


**Reading Hallucination interactive — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Score_spherical,Sigma,deviance,df_residual,logLik,nobs,sigma
0,32947.3984,32947.4057,33040.8024,0.2942,0.3735,0.694,0.5664,0.3479,-inf,0.0008,1.0,26893.084,35989,-16462.6992,36000,1.0


  convergence_status: Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.01019724



*Single RE structure (source_test constant) — no RE comparison.*

### Reading Hallucination — Step 2: Null & additive models

[Reading Hallucination null] Fitting GLMM: read_hallucination ~ 1 + (1 | trace)


**Reading Hallucination null — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Sigma,deviance,df_residual,logLik,nobs,sigma
0,37216.2841,37216.2844,37233.2666,0.6228,0.3616,0.6228,0.0,0.3423,-inf,1.0,26033.3963,35998,-18606.142,36000,1.0


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 1.144863e-06

[Reading Hallucination additive] Fitting GLMM: read_hallucination ~ setsize + fb_exp + model + order_c + (1 | trace)
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.0124318

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.0124318

  ⚠  [Reading Hallucination additive] bobyqa did not converge → trying nloptwrap
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.0124318

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.0124318

  ✓  [Reading Hallucination additive] nloptwrap converged
  ⚠  [Reading Hallucination additive] nloptwrap still did not converge → trying Nelder_Mead
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.0124318

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.0124318

  ✓  [Reading Hallucination additive] Nelder_Mead converged


**Reading Hallucination additive — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Score_spherical,Sigma,deviance,df_residual,logLik,nobs,sigma
0,32966.0602,32966.0663,33050.973,0.2968,0.3734,0.6926,0.5628,0.3479,-inf,0.0008,1.0,26883.1574,35990,-16473.0301,36000,1.0


  convergence_status: Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.0124318



### Reading Hallucination — Step 2: Fixed-effect comparisons

**Reading Hallucination null → additive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,37216.2841,37233.2666,-18606.1420,2.0,37212.2841,NaN,NaN,NaN,
1,32966.0602,33050.9730,-16473.0301,10.0,32946.0602,4266.2238,8.0,0.0,***


**Reading Hallucination additive → interactive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,32966.0602,33050.9730,-16473.0301,10.0,32946.0602,NaN,NaN,NaN,
1,32947.3984,33040.8024,-16462.6992,11.0,32925.3984,20.6618,1.0,0.0,***


### Reading Hallucination — Interactive model results

**Reading Hallucination — Fixed effects**

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value,sig,OR,OR_lo,OR_hi
0,(Intercept),-0.8410,0.0747,-0.9874,-0.6946,-11.2610,inf,0.0000,***,0.4313,0.3726,0.4993
1,setsize40,0.4425,0.0716,0.3022,0.5828,6.1828,inf,0.0000,***,1.5566,1.3529,1.7910
2,fb_expTrue,1.3149,0.0738,1.1702,1.4596,17.8144,inf,0.0000,***,3.7244,3.2228,4.3042
3,modelGemma3:12b-QAT,0.9715,0.0743,0.8259,1.1172,13.0728,inf,0.0000,***,2.6420,2.2839,3.0562
4,modelGemma3:27b,-0.8925,0.0764,-1.0423,-0.7427,-11.6789,inf,0.0000,***,0.4096,0.3527,0.4758
5,modelGemma3:27b-QAT,-0.7313,0.0756,-0.8795,-0.5831,-9.6717,inf,0.0000,***,0.4813,0.4150,0.5582
6,modelLlama4:16x17b,-1.9047,0.0796,-2.0607,-1.7487,-23.9241,inf,0.0000,***,0.1489,0.1274,0.1740
7,modelLlama3.3:70b,-6.2479,0.1878,-6.6160,-5.8798,-33.2675,inf,0.0000,***,0.0019,0.0013,0.0028
8,order_c,0.0533,0.0483,-0.0414,0.1479,1.1026,inf,0.2702,,1.0547,0.9594,1.1594
9,setsize40:fb_expTrue,0.4347,0.0976,0.2434,0.6260,4.4528,inf,0.0000,***,1.5445,1.2755,1.8702


**Reading Hallucination — Type-III ANOVA (Satterthwaite)**

,model term,df1,df2,F_ratio,Chisq,p_value,sig
0,setsize,1.0,inf,181.948,181.948,0.0000,***
1,fb_exp,1.0,inf,935.545,935.545,0.0000,***
2,model,5.0,inf,471.515,2357.575,0.0000,***
3,order_c,1.0,inf,1.216,1.216,0.2702,
4,setsize:fb_exp,1.0,inf,19.827,19.827,0.0000,***


**Reading Hallucination — VIF**

  ✓ All VIF < 5 


,term,vif,ci_increase_factor
0,setsize40,2.000,1.414
1,fb_expTrue,2.000,1.414
2,modelGemma3:12b-QAT,1.667,1.291
3,modelGemma3:27b,1.667,1.291
4,modelGemma3:27b-QAT,1.667,1.291
5,modelLlama4:16x17b,1.667,1.291
6,modelLlama3_3:70b,1.667,1.291
7,order_c,1.000,1.000
8,setsize40:fb_expTrue,3.000,1.732


### Reading Hallucination — Diagnostics

**Reading Hallucination — DHARMa diagnostics**

  [DHARMa — Error in grDevices:::.smoothScatterCalcDensity(x, nbin, bandwidth) : 
  Must have the ('Recommended') package "KernSmooth" installed
]


### Reading Hallucination — Post-hoc contrasts

**Reading Hallucination | fb_exp (H2) — Pairwise emmeans: fb_exp [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,False / True,0.216,0.0108,inf,0.1958,0.2383,1.0,-30.5867,0.0,


**Reading Hallucination | setsize — Pairwise emmeans: setsize [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,setsize20 / setsize40,0.5169,0.0253,inf,0.4697,0.5689,1.0,-13.4888,0.0,


**Reading Hallucination | model (H4) — Pairwise emmeans: model [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,Gemma3:12b / (Gemma3:12b-QAT),0.3785,0.0281,inf,0.3043,0.4708,1.0,-13.0728,0.000,
1,Gemma3:12b / Gemma3:27b,2.4412,0.1866,inf,1.9507,3.0550,1.0,11.6789,0.000,
2,Gemma3:12b / (Gemma3:27b-QAT),2.0778,0.1571,inf,1.6643,2.5942,1.0,9.6717,0.000,
3,Gemma3:12b / Llama4:16x17b,6.7173,0.5348,inf,5.3175,8.4856,1.0,23.9241,0.000,
4,Gemma3:12b / Llama3.3:70b,516.9341,97.0847,inf,297.8708,897.1033,1.0,33.2675,0.000,
5,(Gemma3:12b-QAT) / Gemma3:27b,6.4495,0.5012,inf,5.1341,8.1021,1.0,23.9849,0.000,
6,(Gemma3:12b-QAT) / (Gemma3:27b-QAT),5.4895,0.4217,inf,4.3814,6.8780,1.0,22.1665,0.000,
7,(Gemma3:12b-QAT) / Llama4:16x17b,17.7469,1.4386,inf,13.9892,22.5141,1.0,35.4824,0.000,
8,(Gemma3:12b-QAT) / Llama3.3:70b,1365.7211,257.6662,inf,784.9840,2376.0921,1.0,38.2656,0.000,
9,Gemma3:27b / (Gemma3:27b-QAT),0.8511,0.0661,inf,0.6776,1.0691,1.0,-2.0747,0.038,


**Reading Hallucination — Covariate slopes**

*Covariate: `order_c`*

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value
8,order_c,0.0533,0.0483,-0.0414,0.1479,1.1026,inf,0.2702


## Section 6: Model 2 — Recognition Accuracy (all trials)

In [7]:
# ─────────────────────────────────────────────────────────────────────────────
# 6. Model 2 — Recognition Accuracy (all trials)
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 2 — Recognition Accuracy (all trials)"))
display(Markdown(
    "**Family:** binomial logit.  \n"
    "**2-way interactions:** source_test×setsize, source_test×fb_exp, setsize×fb_exp.  \n"
    "**Covariates:** `rating_cen`, `order_c`, `model`."
))

_ACC_FE_INT = ("source_test + setsize + fb_exp "
               "+ source_test:setsize + source_test:fb_exp + setsize:fb_exp "
               "+ model + order_c + rating_cen")
_ACC_FE_ADD = "source_test + setsize + fb_exp + model + order_c + rating_cen"

ACC_INT_RED = f"accuracy ~ {_ACC_FE_INT} + (1 | trace)"
ACC_INT_MAX = ACC_INT_RED  # (1+source_test|trace) fails (gradient=NA); use (1|trace) throughout

acc_cols = ["accuracy","source_test","setsize","fb_exp","model","order_c","rating_cen",
            "trace","obs_id"]
acc_data = df[acc_cols].dropna()

models_acc = run_analysis_block(
    label           = "Recognition Accuracy",
    int_f_max       = ACC_INT_MAX,
    int_f_red       = ACC_INT_RED,
    add_fe          = _ACC_FE_ADD,
    data            = acc_data,
    family          = "binomial",
    prefix          = "acc",
    has_source_test = True,
    exponentiate    = True,
    covariates      = ["rating_cen", "order_c"],
)

---
## Model 2 — Recognition Accuracy (all trials)

**Family:** binomial logit.  
**2-way interactions:** source_test×setsize, source_test×fb_exp, setsize×fb_exp.  
**Covariates:** `rating_cen`, `order_c`, `model`.

### Recognition Accuracy — Step 1: RE structure selection

[Recognition Accuracy interactive] Fitting GLMM: accuracy ~ source_test + setsize + fb_exp + source_test:setsize + source_test:fb
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.002978373

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.002978373

  ⚠  [Recognition Accuracy interactive] bobyqa did not converge → trying nloptwrap
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.002978373

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.002978373

  ✓  [Recognition Accuracy interactive] nloptwrap converged
  ⚠  [Recognition Accuracy interactive] nloptwrap still did not converge → trying Nelder_Mead
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.002978373

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.002978373

  ✓  [Recognition Accuracy interactive] Nelder_Mead converged


**Recognition Accuracy interactive — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Sigma,deviance,df_residual,logLik,nobs,sigma
0,90282.7514,90282.7581,90420.5177,0.0305,0.609,0.1761,0.1501,0.4584,-inf,1.0,87700.8585,71985,-45126.3757,72000,1.0


  convergence_status: Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.002978373



*Single RE structure (source_test constant) — no RE comparison.*

### Recognition Accuracy — Step 2: Null & additive models

[Recognition Accuracy null] Fitting GLMM: accuracy ~ 1 + (1 | trace)


**Recognition Accuracy null — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Sigma,deviance,df_residual,logLik,nobs,sigma
0,98026.1203,98026.1205,98044.4891,0.0584,0.6492,0.0584,0.0,0.4785,-inf,1.0,93477.698,71998,-49011.0602,72000,1.0


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 1.036729e-06

[Recognition Accuracy additive] Fitting GLMM: accuracy ~ source_test + setsize + fb_exp + model + order_c + rating_cen + (1 | 


**Recognition Accuracy additive — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Sigma,deviance,df_residual,logLik,nobs,sigma
0,93144.952,93144.9564,93255.1651,0.0236,0.6319,0.1204,0.0991,0.4703,-inf,1.0,90989.1295,71988,-46560.476,72000,1.0


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 3.555405e-05



### Recognition Accuracy — Step 2: Fixed-effect comparisons

**Recognition Accuracy null → additive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,98026.1203,98044.4891,-49011.0602,2.0,98022.1203,NaN,NaN,NaN,
1,93144.9520,93255.1651,-46560.4760,12.0,93120.9520,4901.1683,10.0,0.0,***


**Recognition Accuracy additive → interactive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,93144.9520,93255.1651,-46560.4760,12.0,93120.9520,NaN,NaN,NaN,
1,90282.7514,90420.5177,-45126.3757,15.0,90252.7514,2868.2006,3.0,0.0,***


### Recognition Accuracy — Interactive model results

**Recognition Accuracy — Fixed effects**

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value,sig,OR,OR_lo,OR_hi
0,(Intercept),0.8316,0.0372,0.7587,0.9046,22.3346,inf,0.0000,***,2.2971,2.1354,2.4710
1,source_testtest:imagined,-1.7663,0.0347,-1.8342,-1.6983,-50.9440,inf,0.0000,***,0.1710,0.1597,0.1830
2,setsize40,-0.0420,0.0343,-0.1093,0.0254,-1.2219,inf,0.2218,,0.9589,0.8965,1.0257
3,fb_expTrue,-0.9078,0.0363,-0.9789,-0.8367,-25.0360,inf,0.0000,***,0.4034,0.3757,0.4331
4,modelGemma3:12b-QAT,0.2021,0.0323,0.1388,0.2653,6.2639,inf,0.0000,***,1.2239,1.1489,1.3038
5,modelGemma3:27b,0.4740,0.0323,0.4107,0.5373,14.6677,inf,0.0000,***,1.6064,1.5078,1.7115
6,modelGemma3:27b-QAT,0.3912,0.0323,0.3279,0.4546,12.1007,inf,0.0000,***,1.4788,1.3880,1.5755
7,modelLlama4:16x17b,0.3773,0.0321,0.3144,0.4403,11.7523,inf,0.0000,***,1.4584,1.3695,1.5531
8,modelLlama3.3:70b,1.5103,0.0355,1.4407,1.5799,42.5173,inf,0.0000,***,4.5282,4.2237,4.8547
9,order_c,0.0139,0.0188,-0.0230,0.0508,0.7378,inf,0.4606,,1.0140,0.9772,1.0521


**Recognition Accuracy — Type-III ANOVA (Satterthwaite)**

,model term,df1,df2,F_ratio,Chisq,p_value,sig
0,source_test,1.0,inf,2594.877,2594.877,0.0000,***
1,setsize,1.0,inf,79.757,79.757,0.0000,***
2,fb_exp,1.0,inf,42.490,42.490,0.0000,***
3,model,5.0,inf,405.409,2027.045,0.0000,***
4,order_c,1.0,inf,0.544,0.544,0.4606,
5,rating_cen,1.0,inf,171.592,171.592,0.0000,***
6,source_test:setsize,1.0,inf,6.686,6.686,0.0097,**
7,source_test:fb_exp,1.0,inf,2734.102,2734.102,0.0000,***
8,setsize:fb_exp,1.0,inf,20.697,20.697,0.0000,***


**Recognition Accuracy — VIF**

  ✓ All VIF < 5 


,term,vif,ci_increase_factor
0,source_testtest:imagined,3.447,1.857
1,setsize40,2.731,1.653
2,fb_expTrue,3.148,1.774
3,modelGemma3:12b-QAT,1.467,1.211
4,modelGemma3:27b,1.342,1.159
5,modelGemma3:27b-QAT,1.348,1.161
6,modelLlama4:16x17b,1.218,1.104
7,modelLlama3_3:70b,1.406,1.186
8,order_c,1.001,1.000
9,rating_cen,1.129,1.062


### Recognition Accuracy — Diagnostics

**Recognition Accuracy — DHARMa diagnostics**

  [DHARMa — Error in grDevices:::.smoothScatterCalcDensity(x, nbin, bandwidth) : 
  Must have the ('Recommended') package "KernSmooth" installed
]


### Recognition Accuracy — Post-hoc contrasts

**Recognition Accuracy | source_test (H1) — Pairwise emmeans: source_test [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,test:perceived / test:imagined,2.5698,0.0476,inf,2.4782,2.6649,1.0,50.9399,0.0,


**Recognition Accuracy | fb_exp (H2) — Pairwise emmeans: fb_exp [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,False / True,1.1389,0.0227,inf,1.0952,1.1843,1.0,6.5184,0.0,


**Recognition Accuracy | source_test × fb_exp (H3) — Pairwise emmeans: source_test | fb_exp [fdr]**

  [emmeans — '<' not supported between instances of 'str' and 'float']


**Recognition Accuracy | fb_exp × source_test (H3) — Pairwise emmeans: fb_exp | source_test [fdr]**

,contrast,source_test,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,False / True,test:perceived,2.7103,0.0730,inf,2.5708,2.8573,1.0,36.9990,0.0,
1,False / True,test:imagined,0.4786,0.0119,inf,0.4558,0.5025,1.0,-29.5961,0.0,


**Recognition Accuracy | setsize — Pairwise emmeans: setsize [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,setsize20 / setsize40,1.1921,0.0235,inf,1.147,1.239,1.0,8.9307,0.0,


**Recognition Accuracy | model (H4) — Pairwise emmeans: model [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,Gemma3:12b / (Gemma3:12b-QAT),0.8170,0.0264,inf,0.7432,0.8982,1.0,-6.2639,0.0000,
1,Gemma3:12b / Gemma3:27b,0.6225,0.0201,inf,0.5662,0.6844,1.0,-14.6677,0.0000,
2,Gemma3:12b / (Gemma3:27b-QAT),0.6762,0.0219,inf,0.6150,0.7435,1.0,-12.1007,0.0000,
3,Gemma3:12b / Llama4:16x17b,0.6857,0.0220,inf,0.6240,0.7534,1.0,-11.7523,0.0000,
4,Gemma3:12b / Llama3.3:70b,0.2208,0.0078,inf,0.1990,0.2451,1.0,-42.5173,0.0000,
5,(Gemma3:12b-QAT) / Gemma3:27b,0.7619,0.0250,inf,0.6919,0.8389,1.0,-8.2867,0.0000,
6,(Gemma3:12b-QAT) / (Gemma3:27b-QAT),0.8276,0.0271,inf,0.7517,0.9112,1.0,-5.7730,0.0000,
7,(Gemma3:12b-QAT) / Llama4:16x17b,0.8392,0.0272,inf,0.7631,0.9229,1.0,-5.4100,0.0000,
8,(Gemma3:12b-QAT) / Llama3.3:70b,0.2703,0.0098,inf,0.2430,0.3006,1.0,-36.1438,0.0000,
9,Gemma3:27b / (Gemma3:27b-QAT),1.0863,0.0349,inf,0.9884,1.1939,1.0,2.5731,0.0108,


**Recognition Accuracy — Covariate slopes**

*Covariate: `rating_cen`*

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value
10,rating_cen,0.0063,0.0005,0.0053,0.0072,13.0993,inf,0.0


*Covariate: `order_c`*

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value
9,order_c,0.0139,0.0188,-0.023,0.0508,0.7378,inf,0.4606


### Manuscript cross-reference — Accuracy GLMM source contrast

The output block above (Model 2 — Recognition Accuracy) already computes
the emmeans source contrast as part of `run_analysis_block`. The key value
reported in `main.tex` is (updated 2026-06-17 after ACC_INT_MAX fix — was OR=4.261 from non-converged model):

```
test:perceived / test:imagined  OR = 2.571  SE = 0.047  CI = [2.480, 2.663]  z = 51.48  p < .001  (updated 2026-06-17)
```

This appears in the cell above under the heading **'Pairwise source contrast (source_test)'**.
If re-running, the standalone call below reproduces this contrast explicitly.

In [8]:
# Explicit source contrast — Accuracy GLMM (manuscript main.tex §Experiment 2 Accuracy)
# Reported in text: OR = 2.57, 95% CI [2.48, 2.66], z = 51.48, p < .001  (updated 2026-06-17)
# Run this cell only after models_acc has been fitted in Cell 13 above.

import rpy2.robjects as ro
from rpy2.robjects import pandas2ri

# Export the winning interactive model to R's global env so emmeans() can find it.
# run_analysis_block stores models in Python only; ACC_INT_MAX=ACC_INT_RED so
# models_acc['interactive'] is the (1|trace) interactive model.
ro.globalenv['acc_int_max'] = models_acc['interactive'].r_model
ro.r("""
library(emmeans)
em_src_acc <- emmeans(acc_int_max, ~ source_test, type = 'response')
cat('\n=== Accuracy GLMM: source emmeans contrast (perceived / imagined) ===\n')
print(contrast(em_src_acc, method = 'pairwise'))
""")


In [25]:
# Explicit source contrast — Accuracy GLMM (manuscript main.tex §Experiment 2 Accuracy)
# Reported in text: OR = 2.57, 95% CI [2.48, 2.66], z = 51.48, p < .001
pairwise(models_acc['interactive'], 'source_test', label='Accuracy GLMM — source contrast')

**Accuracy GLMM — source contrast — Pairwise emmeans: source_test [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,test:perceived / test:imagined,2.5698,0.0476,inf,2.4782,2.6649,1.0,50.9399,0.0,


,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,test:perceived / test:imagined,2.569831,0.047615,inf,2.478182,2.66487,1.0,50.939935,0.0,


## Section 7: Model 2P — Accuracy, perceived + read_hallucination

In [9]:
# ─────────────────────────────────────────────────────────────────────────────
# 7. Model 2P — Accuracy, perceived trials + read_hallucination
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 2P — Accuracy (perceived trials + read_hallucination)"))
display(Markdown(
    "Supplementary model restricted to `test:perceived` trials.  \n"
    "`read_hallucination` as predictor tests whether compliance moderates accuracy.  \n"
    "**RE:** `(1|trace)` only — source_test is constant in this subset."
))

_ACC_P_FE_INT = ("setsize * fb_exp + model + order_c + rating_cen + read_hallucination")
_ACC_P_FE_ADD = "setsize + fb_exp + model + order_c + rating_cen + read_hallucination"

ACC_P_INT = f"accuracy ~ {_ACC_P_FE_INT} + (1 | trace)"

acc_p_cols = ["accuracy","setsize","fb_exp","model","order_c","rating_cen",
              "read_hallucination","trace","obs_id"]
acc_p_data = df_perc[acc_p_cols].dropna()

models_acc_p = run_analysis_block(
    label           = "Accuracy (perceived)",
    int_f_max       = ACC_P_INT,
    int_f_red       = ACC_P_INT,
    add_fe          = _ACC_P_FE_ADD,
    data            = acc_p_data,
    family          = "binomial",
    prefix          = "acc_p",
    has_source_test = False,
    exponentiate    = True,
    covariates      = ["rating_cen", "order_c", "read_hallucination"],
)

---
## Model 2P — Accuracy (perceived trials + read_hallucination)

Supplementary model restricted to `test:perceived` trials.  
`read_hallucination` as predictor tests whether compliance moderates accuracy.  
**RE:** `(1|trace)` only — source_test is constant in this subset.

### Accuracy (perceived) — Step 1: RE structure selection

[Accuracy (perceived) interactive] Fitting GLMM: accuracy ~ setsize * fb_exp + model + order_c + rating_cen + read_hallucination 
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.04538691

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.04538691

  ⚠  [Accuracy (perceived) interactive] bobyqa did not converge → trying nloptwrap
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.04538691

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.04538691

  ✓  [Accuracy (perceived) interactive] nloptwrap converged
  ⚠  [Accuracy (perceived) interactive] nloptwrap still did not converge → trying Nelder_Mead
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.04538691

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.04538691

  ✓  [Accuracy (perceived) interactive] Nelder_Mead converged


**Accuracy (perceived) interactive — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Sigma,deviance,df_residual,logLik,nobs,sigma
0,39061.4422,39061.4523,39171.8288,0.3996,0.4247,0.5073,0.1794,0.3737,-inf,1.0,30581.5415,35987,-19517.7211,36000,1.0


  convergence_status: Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.04538691



*Single RE structure (source_test constant) — no RE comparison.*

### Accuracy (perceived) — Step 2: Null & additive models

[Accuracy (perceived) null] Fitting GLMM: accuracy ~ 1 + (1 | trace)


**Accuracy (perceived) null — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Sigma,deviance,df_residual,logLik,nobs,sigma
0,40906.5486,40906.5489,40923.5311,0.4475,0.4365,0.4475,0.0,0.3784,-inf,1.0,31430.5277,35998,-20451.2743,36000,1.0


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 4.990429e-05

[Accuracy (perceived) additive] Fitting GLMM: accuracy ~ setsize + fb_exp + model + order_c + rating_cen + read_hallucination 
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.05343537

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.05343537

  ⚠  [Accuracy (perceived) additive] bobyqa did not converge → trying nloptwrap
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.05343537

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.05343537

  ✓  [Accuracy (perceived) additive] nloptwrap converged
  ⚠  [Accuracy (perceived) additive] nloptwrap still did not converge → trying Nelder_Mead
R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.05343537

R messages: 
Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.05343537

  ✓  [Accuracy (perceived) additive] Nelder_Mead converged


**Accuracy (perceived) additive — Fit statistics**

,AIC,AICc,BIC,ICC,Log_loss,R2_conditional,R2_marginal,RMSE,Score_log,Sigma,deviance,df_residual,logLik,nobs,sigma
0,39059.1365,39059.1452,39161.0318,0.3999,0.4246,0.5087,0.1813,0.3736,-inf,1.0,30574.5075,35988,-19517.5683,36000,1.0


  convergence_status: Convergence status
: [1] FALSE
attr(,"gradient")
[1] 0.05343537



### Accuracy (perceived) — Step 2: Fixed-effect comparisons

**Accuracy (perceived) null → additive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,40906.5486,40923.5311,-20451.2743,2.0,40902.5486,NaN,NaN,NaN,
1,39059.1365,39161.0318,-19517.5683,12.0,39035.1365,1867.4121,10.0,0.0,***


**Accuracy (perceived) additive → interactive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,39059.1365,39161.0318,-19517.5683,12.0,39035.1365,NaN,NaN,NaN,
1,39061.4422,39171.8288,-19517.7211,13.0,39035.4422,0.0,1.0,1.0,


### Accuracy (perceived) — Interactive model results

**Accuracy (perceived) — Fixed effects**

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value,sig,OR,OR_lo,OR_hi
0,(Intercept),1.7678,0.0937,1.5841,1.9514,18.8639,inf,0.0000,***,5.8577,4.8748,7.0387
1,setsize40,-0.3460,0.0820,-0.5067,-0.1853,-4.2194,inf,0.0000,***,0.7075,0.6025,0.8309
2,fb_expTrue,-1.8092,0.0853,-1.9763,-1.6421,-21.2196,inf,0.0000,***,0.1638,0.1386,0.1936
3,modelGemma3:12b-QAT,-1.0729,0.0922,-1.2537,-0.8922,-11.6361,inf,0.0000,***,0.3420,0.2855,0.4098
4,modelGemma3:27b,0.0111,0.0931,-0.1713,0.1935,0.1189,inf,0.9054,,1.0111,0.8425,1.2134
5,modelGemma3:27b-QAT,0.9014,0.0967,0.7119,1.0909,9.3220,inf,0.0000,***,2.4630,2.0378,2.9769
6,modelLlama4:16x17b,-0.5438,0.0920,-0.7240,-0.3635,-5.9123,inf,0.0000,***,0.5806,0.4848,0.6952
7,modelLlama3.3:70b,1.3734,0.1009,1.1756,1.5712,13.6116,inf,0.0000,***,3.9488,3.2402,4.8122
8,order_c,0.3979,0.0536,0.2929,0.5029,7.4293,inf,0.0000,***,1.4887,1.3403,1.6535
9,rating_cen,0.0105,0.0007,0.0091,0.0118,15.2081,inf,0.0000,***,1.0105,1.0092,1.0119


**Accuracy (perceived) — Type-III ANOVA (Satterthwaite)**

,model term,df1,df2,F_ratio,Chisq,p_value,sig
0,setsize,1.0,inf,34.708,34.708,0.0000,***
1,fb_exp,1.0,inf,900.536,900.536,0.0000,***
2,model,5.0,inf,154.375,771.875,0.0000,***
3,order_c,1.0,inf,55.194,55.194,0.0000,***
4,rating_cen,1.0,inf,231.286,231.286,0.0000,***
5,read_hallucination,1.0,inf,183.110,183.110,0.0000,***
6,setsize:fb_exp,1.0,inf,0.168,0.168,0.6819,


**Accuracy (perceived) — VIF**

  ✓ All VIF < 5 


,term,vif,ci_increase_factor
0,setsize40,1.920,1.386
1,fb_expTrue,2.378,1.542
2,modelGemma3:12b-QAT,1.404,1.185
3,modelGemma3:27b,1.296,1.139
4,modelGemma3:27b-QAT,1.307,1.143
5,modelLlama4:16x17b,1.232,1.110
6,modelLlama3_3:70b,1.500,1.225
7,order_c,1.002,1.001
8,rating_cen,1.081,1.040
9,read_hallucination,1.218,1.104


### Accuracy (perceived) — Diagnostics

**Accuracy (perceived) — DHARMa diagnostics**

  [DHARMa — Error in grDevices:::.smoothScatterCalcDensity(x, nbin, bandwidth) : 
  Must have the ('Recommended') package "KernSmooth" installed
]


### Accuracy (perceived) — Post-hoc contrasts

**Accuracy (perceived) | fb_exp (H2) — Pairwise emmeans: fb_exp [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,False / True,5.9708,0.3555,inf,5.3131,6.7099,1.0,30.0089,0.0,


**Accuracy (perceived) | setsize — Pairwise emmeans: setsize [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,setsize20 / setsize40,1.3822,0.0759,inf,1.2411,1.5393,1.0,5.8914,0.0,


**Accuracy (perceived) | model (H4) — Pairwise emmeans: model [fdr]**

,contrast,odds_ratio,SE,df,asymp_LCL,asymp_UCL,null,z_ratio,p_value,sig
0,Gemma3:12b / (Gemma3:12b-QAT),2.9239,0.2696,inf,2.2306,3.8327,1.0,11.6361,0.0000,
1,Gemma3:12b / Gemma3:27b,0.9890,0.0920,inf,0.7526,1.2996,1.0,-0.1189,0.9054,
2,Gemma3:12b / (Gemma3:27b-QAT),0.4060,0.0393,inf,0.3057,0.5393,1.0,-9.3220,0.0000,
3,Gemma3:12b / Llama4:16x17b,1.7225,0.1584,inf,1.3150,2.2563,1.0,5.9123,0.0000,
4,Gemma3:12b / Llama3.3:70b,0.2532,0.0256,inf,0.1883,0.3405,1.0,-13.6116,0.0000,
5,(Gemma3:12b-QAT) / Gemma3:27b,0.3382,0.0313,inf,0.2577,0.4439,1.0,-11.7015,0.0000,
6,(Gemma3:12b-QAT) / (Gemma3:27b-QAT),0.1389,0.0136,inf,0.1042,0.1850,1.0,-20.2119,0.0000,
7,(Gemma3:12b-QAT) / Llama4:16x17b,0.5891,0.0538,inf,0.4506,0.7701,1.0,-5.7969,0.0000,
8,(Gemma3:12b-QAT) / Llama3.3:70b,0.0866,0.0091,inf,0.0637,0.1177,1.0,-23.4094,0.0000,
9,Gemma3:27b / (Gemma3:27b-QAT),0.4105,0.0394,inf,0.3097,0.5442,1.0,-9.2703,0.0000,


**Accuracy (perceived) — Covariate slopes**

*Covariate: `rating_cen`*

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value
9,rating_cen,0.0105,0.0007,0.0091,0.0118,15.2081,inf,0.0


*Covariate: `order_c`*

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value
8,order_c,0.3979,0.0536,0.2929,0.5029,7.4293,inf,0.0


*Covariate: `read_hallucination`*

,term,estimate,std_error,conf_low,conf_high,z_stat,df,p_value
10,read_hallucination,0.5061,0.0374,0.4328,0.5794,13.5318,inf,0.0


## Section 8: Model 3 — Relatedness Rating (all trials)

In [10]:
# ─────────────────────────────────────────────────────────────────────────────
# 8. Model 3 — Relatedness Rating (all trials)
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 3 — Relatedness Rating (all trials)"))
display(Markdown(
    "**Outcome:** `rating_cen` (centred, not z-scored).  \n"
    "**Family:** Gaussian identity.  \n"
    "**Covariates:** `order_c`, `model`.  \n"
    "Note: `rating_cen` is the outcome here, not a covariate."
))

_RR_FE_INT = ("source_test + setsize + fb_exp "
              "+ source_test:setsize + source_test:fb_exp + setsize:fb_exp "
              "+ model + order_c")
_RR_FE_ADD = "source_test + setsize + fb_exp + model + order_c"

RR_INT_MAX = f"rating_cen ~ {_RR_FE_INT} + (1 + source_test | trace)"
RR_INT_RED = f"rating_cen ~ {_RR_FE_INT} + (1 | trace)"

rr_cols = ["rating_cen","source_test","setsize","fb_exp","model","order_c","trace"]
rr_data = df[rr_cols].dropna()

models_rr = run_analysis_block(
    label           = "Relatedness Rating",
    int_f_max       = RR_INT_MAX,
    int_f_red       = RR_INT_RED,
    add_fe          = _RR_FE_ADD,
    data            = rr_data,
    family          = "gaussian",
    prefix          = "rr",
    has_source_test = True,
    covariates      = ["order_c"],
)

---
## Model 3 — Relatedness Rating (all trials)

**Outcome:** `rating_cen` (centred, not z-scored).  
**Family:** Gaussian identity.  
**Covariates:** `order_c`, `model`.  
Note: `rating_cen` is the outcome here, not a covariate.

### Relatedness Rating — Step 1: RE structure selection

*Probing maximal RE `(1+source_test|trace)` — any isSingular warning below is expected at this step and will be handled automatically.*

[Relatedness Rating int-max] Fitting LMM: rating_cen ~ source_test + setsize + fb_exp + source_test:setsize + source_test:
R messages: 
boundary (singular) fit: see help('isSingular')

Random effect variances not available. Returned R2 does not account for random effects.

R messages: 
boundary (singular) fit: see help('isSingular')

Random effect variances not available. Returned R2 does not account for random effects.



**Relatedness Rating int-max — Fit statistics**

,AIC,AICc,BIC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,616211.9916,616212.0001,616368.1268,-2147483648,0.2101,616177.9916,16.4003,16.7888,71983,-308088.9958,72000,16.7888


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 3.038387e-07



*Relatedness Rating: Maximal RE is singular (boundary solution — random slope variance ≈ 0) → reduced RE `(1|trace)` selected throughout. This is the correct outcome.*

[Relatedness Rating int-red] Fitting LMM: rating_cen ~ source_test + setsize + fb_exp + source_test:setsize + source_test:


**Relatedness Rating int-red — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,619476.0601,619476.0668,619613.8264,0.0208,0.2367,0.2204,619446.0601,17.5592,17.7008,71985,-309723.0301,72000,17.7008


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 2.075997e-09



### Relatedness Rating — Step 2: Null & additive models

[Relatedness Rating null] Fitting LMM: rating_cen ~ 1 + (1 | trace)


**Relatedness Rating null — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,633845.0595,633845.0599,633872.6128,0.1117,0.1117,0.0,633839.0595,18.6628,19.0716,71997,-316919.5298,72000,19.0716


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 1.609372e-09

[Relatedness Rating additive] Fitting LMM: rating_cen ~ source_test + setsize + fb_exp + model + order_c + (1 | trace)


**Relatedness Rating additive — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,620746.2561,620746.2605,620856.4692,0.0195,0.2223,0.2068,620722.2561,17.7323,17.8677,71988,-310361.1281,72000,17.8677


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 1.065708e-08



### Relatedness Rating — Step 2: Fixed-effect comparisons

**Relatedness Rating null → additive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,633845.0595,633872.6128,-316919.5298,3.0,633836.6957,NaN,NaN,NaN,
1,620746.2561,620856.4692,-310361.1281,12.0,620705.3351,13131.3606,9.0,0.0,***


**Relatedness Rating additive → interactive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,620746.2561,620856.4692,-310361.1281,12.0,620705.3351,NaN,NaN,NaN,
1,619476.0601,619613.8264,-309723.0301,15.0,619427.1056,1278.2295,3.0,0.0,***


### Relatedness Rating — Interactive model results

**Relatedness Rating — Fixed effects**

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value,sig
0,(Intercept),-11.5318,0.2902,-12.1006,-10.9629,-39.7348,10502.7964,0.0000,***
1,source_testtest:imagined,17.7696,0.2639,17.2524,18.2867,67.3426,67913.7773,0.0000,***
2,setsize40,2.8826,0.2643,2.3646,3.4007,10.9069,12094.1348,0.0000,***
3,fb_expTrue,11.8656,0.2841,11.3086,12.4225,41.7610,15712.7559,0.0000,***
4,modelGemma3:12b-QAT,7.2148,0.2652,6.6950,7.7347,27.2080,4939.6769,0.0000,***
5,modelGemma3:27b,-6.3809,0.2652,-6.9007,-5.8610,-24.0631,4939.6769,0.0000,***
6,modelGemma3:27b-QAT,-4.8979,0.2652,-5.4177,-4.3780,-18.4705,4939.6769,0.0000,***
7,modelLlama4:16x17b,-2.0723,0.2652,-2.5921,-1.5524,-7.8148,4939.6769,0.0000,***
8,modelLlama3.3:70b,-10.4730,0.2652,-10.9929,-9.9532,-39.4950,4939.6769,0.0000,***
9,order_c,0.3488,0.1531,0.0487,0.6489,2.2783,4939.6769,0.0228,*


**Relatedness Rating — Type-III ANOVA (Satterthwaite)**

,model term,df1,df2,F_ratio,Chisq,p_value,sig
0,source_test,1.0,inf,8397.668,8397.668,0.0000,***
1,setsize,1.0,inf,251.008,251.008,0.0000,***
2,fb_exp,1.0,inf,1935.429,1935.429,0.0000,***
3,model,5.0,inf,1051.011,5255.055,0.0000,***
4,order_c,1.0,inf,5.191,5.191,0.0227,*
5,source_test:setsize,1.0,inf,2.315,2.315,0.1281,
6,source_test:fb_exp,1.0,inf,1286.929,1286.929,0.0000,***
7,setsize:fb_exp,1.0,inf,0.993,0.993,0.3191,


**Relatedness Rating — VIF**

  ✓ All VIF < 5 


,term,vif,ci_increase_factor
0,source_testtest:imagined,3.000,1.732
1,setsize40,3.000,1.732
2,fb_expTrue,3.000,1.732
3,modelGemma3:12b-QAT,1.667,1.291
4,modelGemma3:27b,1.667,1.291
5,modelGemma3:27b-QAT,1.667,1.291
6,modelLlama4:16x17b,1.667,1.291
7,modelLlama3_3:70b,1.667,1.291
8,order_c,1.000,1.000
9,source_testtest:imagined:setsize40,3.000,1.732


### Relatedness Rating — Diagnostics

  [LMM diagnostics skipped for large Gaussian model — results unaffected]


### Relatedness Rating — Post-hoc contrasts

**Relatedness Rating | source_test (H1) — Pairwise emmeans: source_test [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,test:perceived - test:imagined,-12.8237,0.1399,inf,-13.0979,-12.5494,-91.6388,0.0,***


**Relatedness Rating | fb_exp (H2) — Pairwise emmeans: fb_exp [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,False - True,-6.9746,0.1585,inf,-7.2854,-6.6639,-43.9935,0.0,***


**Relatedness Rating | source_test × fb_exp (H3) — Pairwise emmeans: source_test | fb_exp [fdr]**

  [emmeans — '<' not supported between instances of 'str' and 'float']


**Relatedness Rating | fb_exp × source_test (H3) — Pairwise emmeans: fb_exp | source_test [fdr]**

,contrast,source_test,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,False - True,test:perceived,-11.7076,0.2063,inf,-12.1118,-11.3033,-56.7630,0.0,***
1,False - True,test:imagined,-2.2417,0.2063,inf,-2.6459,-1.8374,-10.8684,0.0,***


**Relatedness Rating | setsize — Pairwise emmeans: setsize [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,setsize20 - setsize40,-2.5118,0.1585,inf,-2.8225,-2.201,-15.8432,0.0,***


**Relatedness Rating | model (H4) — Pairwise emmeans: model [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,Gemma3:12b - (Gemma3:12b-QAT),-7.2148,0.2652,inf,-7.9932,-6.4365,-27.2080,0.0,***
1,Gemma3:12b - Gemma3:27b,6.3809,0.2652,inf,5.6025,7.1592,24.0631,0.0,
2,Gemma3:12b - (Gemma3:27b-QAT),4.8979,0.2652,inf,4.1196,5.6762,18.4705,0.0,
3,Gemma3:12b - Llama4:16x17b,2.0723,0.2652,inf,1.2939,2.8506,7.8148,0.0,
4,Gemma3:12b - Llama3.3:70b,10.4730,0.2652,inf,9.6947,11.2513,39.4950,0.0,
5,(Gemma3:12b-QAT) - Gemma3:27b,13.5957,0.2652,inf,12.8174,14.3741,51.2711,0.0,
6,(Gemma3:12b-QAT) - (Gemma3:27b-QAT),12.1127,0.2652,inf,11.3344,12.8911,45.6785,0.0,
7,(Gemma3:12b-QAT) - Llama4:16x17b,9.2871,0.2652,inf,8.5088,10.0655,35.0228,0.0,
8,(Gemma3:12b-QAT) - Llama3.3:70b,17.6879,0.2652,inf,16.9095,18.4662,66.7030,0.0,
9,Gemma3:27b - (Gemma3:27b-QAT),-1.4830,0.2652,inf,-2.2613,-0.7047,-5.5926,0.0,***


**Relatedness Rating — Covariate slopes**

*Covariate: `order_c`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
9,order_c,0.3488,0.1531,0.0487,0.6489,2.2783,4939.6769,0.0228


## Section 9: Model 3P — Rating, perceived + read_hallucination

In [11]:
# ─────────────────────────────────────────────────────────────────────────────
# 9. Model 3P — Rating, perceived + read_hallucination
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 3P — Relatedness Rating (perceived + read_hallucination)"))

_RR_P_FE_INT = "setsize * fb_exp + model + order_c + read_hallucination"
_RR_P_FE_ADD = "setsize + fb_exp + model + order_c + read_hallucination"
RR_P_INT     = f"rating_cen ~ {_RR_P_FE_INT} + (1 | trace)"

rr_p_cols = ["rating_cen","setsize","fb_exp","model","order_c","read_hallucination","trace"]
rr_p_data = df_perc[rr_p_cols].dropna()

models_rr_p = run_analysis_block(
    label           = "Rating (perceived)",
    int_f_max       = RR_P_INT,
    int_f_red       = RR_P_INT,
    add_fe          = _RR_P_FE_ADD,
    data            = rr_p_data,
    family          = "gaussian",
    prefix          = "rr_p",
    has_source_test = False,
    covariates      = ["order_c", "read_hallucination"],
)

---
## Model 3P — Relatedness Rating (perceived + read_hallucination)

### Rating (perceived) — Step 1: RE structure selection

[Rating (perceived) interactive] Fitting LMM: rating_cen ~ setsize * fb_exp + model + order_c + read_hallucination + (1 | trac


**Rating (perceived) interactive — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,327148.9478,327148.9579,327259.3344,0.0206,0.2239,0.2076,327122.9478,22.3227,22.5289,35987,-163561.4739,36000,22.5289


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 6.505227e-08



*Single RE structure (source_test constant) — no RE comparison.*

### Rating (perceived) — Step 2: Null & additive models

[Rating (perceived) null] Fitting LMM: rating_cen ~ 1 + (1 | trace)


**Rating (perceived) null — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,332153.904,332153.9046,332179.3778,0.2056,0.2056,0.0,332147.904,21.7403,22.7363,35997,-166073.952,36000,22.7363


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 4.442137e-09

[Rating (perceived) additive] Fitting LMM: rating_cen ~ setsize + fb_exp + model + order_c + read_hallucination + (1 | trac


**Rating (perceived) additive — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,327147.8764,327147.885,327249.7716,0.0207,0.224,0.2076,327123.8764,22.3224,22.5285,35988,-163561.9382,36000,22.5285


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 6.552436e-08



### Rating (perceived) — Step 2: Fixed-effect comparisons

**Rating (perceived) null → additive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,332153.9040,332179.3778,-166073.9520,3.0,332146.6037,NaN,NaN,NaN,
1,327147.8764,327249.7716,-163561.9382,12.0,327117.8907,5028.7129,9.0,0.0,***


**Rating (perceived) additive → interactive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,327147.8764,327249.7716,-163561.9382,12.0,327117.8907,NaN,NaN,NaN,
1,327148.9478,327259.3344,-163561.4739,13.0,327117.5588,0.3319,1.0,0.5645,


### Rating (perceived) — Interactive model results

**Rating (perceived) — Fixed effects**

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value,sig
0,(Intercept),-7.3237,0.4544,-8.2145,-6.4329,-16.1174,6267.6940,0.0000,***
1,setsize40,3.0989,0.3810,2.3519,3.8458,8.1332,5621.8457,0.0000,***
2,fb_expTrue,12.3277,0.4358,11.4734,13.1820,28.2865,9287.8258,0.0000,***
3,modelGemma3:12b-QAT,9.4628,0.4490,8.5826,10.3431,21.0759,4070.9262,0.0000,***
4,modelGemma3:27b,-8.9172,0.4475,-9.7946,-8.0398,-19.9254,4021.7981,0.0000,***
5,modelGemma3:27b-QAT,-6.9357,0.4470,-7.8121,-6.0594,-15.5169,4007.6767,0.0000,***
6,modelLlama4:16x17b,-8.5798,0.4552,-9.4722,-7.6874,-18.8497,4216.0717,0.0000,***
7,modelLlama3.3:70b,-25.0714,0.4748,-26.0022,-24.1406,-52.8034,4803.3837,0.0000,***
8,order_c,0.6215,0.2573,0.1171,1.1259,2.4159,3972.5968,0.0157,*
9,read_hallucination,-2.0119,0.2958,-2.5915,-1.4322,-6.8024,27032.5578,0.0000,***


**Rating (perceived) — Type-III ANOVA (Satterthwaite)**

,model term,df1,df2,F_ratio,Chisq,p_value,sig
0,setsize,1.0,inf,118.116,118.116,0.0000,***
1,fb_exp,1.0,inf,1935.051,1935.051,0.0000,***
2,model,5.0,inf,1037.220,5186.100,0.0000,***
3,order_c,1.0,inf,5.837,5.837,0.0157,*
4,read_hallucination,1.0,inf,46.273,46.273,0.0000,***
5,setsize:fb_exp,1.0,inf,0.329,0.329,0.5663,


**Rating (perceived) — VIF**

  ✓ All VIF < 5 


,term,vif,ci_increase_factor
0,setsize40,2.091,1.446
1,fb_expTrue,2.016,1.420
2,modelGemma3:12b-QAT,1.652,1.285
3,modelGemma3:27b,1.652,1.285
4,modelGemma3:27b-QAT,1.652,1.285
5,modelLlama4:16x17b,1.652,1.285
6,modelLlama3_3:70b,1.549,1.245
7,order_c,1.000,1.000
8,read_hallucination,1.016,1.008
9,setsize40:fb_expTrue,3.091,1.758


### Rating (perceived) — Diagnostics

  [LMM diagnostics skipped for large Gaussian model — results unaffected]


### Rating (perceived) — Post-hoc contrasts

**Rating (perceived) | fb_exp (H2) — Pairwise emmeans: fb_exp [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,False - True,-12.1733,0.2767,inf,-12.7157,-11.6309,-43.9892,0.0,***


**Rating (perceived) | setsize — Pairwise emmeans: setsize [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,setsize20 - setsize40,-2.9445,0.2709,inf,-3.4755,-2.4135,-10.8681,0.0,***


**Rating (perceived) | model (H4) — Pairwise emmeans: model [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,Gemma3:12b - (Gemma3:12b-QAT),-9.4628,0.4490,inf,-10.7807,-8.1450,-21.0759,0.0000,***
1,Gemma3:12b - Gemma3:27b,8.9172,0.4475,inf,7.6036,10.2307,19.9254,0.0000,
2,Gemma3:12b - (Gemma3:27b-QAT),6.9357,0.4470,inf,5.6238,8.2477,15.5169,0.0000,
3,Gemma3:12b - Llama4:16x17b,8.5798,0.4552,inf,7.2438,9.9158,18.8497,0.0000,
4,Gemma3:12b - Llama3.3:70b,25.0714,0.4748,inf,23.6778,26.4651,52.8034,0.0000,
5,(Gemma3:12b-QAT) - Gemma3:27b,18.3800,0.4560,inf,17.0414,19.7186,40.3032,0.0000,
6,(Gemma3:12b-QAT) - (Gemma3:27b-QAT),16.3986,0.4547,inf,15.0638,17.7333,36.0620,0.0000,
7,(Gemma3:12b-QAT) - Llama4:16x17b,18.0426,0.4696,inf,16.6643,19.4210,38.4206,0.0000,
8,(Gemma3:12b-QAT) - Llama3.3:70b,34.5342,0.4966,inf,33.0765,35.9920,69.5353,0.0000,
9,Gemma3:27b - (Gemma3:27b-QAT),-1.9814,0.4456,inf,-3.2894,-0.6735,-4.4465,0.0000,***


**Rating (perceived) — Covariate slopes**

*Covariate: `order_c`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
8,order_c,0.6215,0.2573,0.1171,1.1259,2.4159,3972.5968,0.0157


*Covariate: `read_hallucination`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
9,read_hallucination,-2.0119,0.2958,-2.5915,-1.4322,-6.8024,27032.5578,0.0


## Section 10: Model 4 — Confidence (all trials)

> **Note (2026-06-14):** This Gaussian LMM analysis of Confidence is exploratory and is **not** the model reported in `main.tex`. The Confidence results reported in the manuscript come from the ordinal Cumulative Link Model fit separately in `notebooks/04_exp2/exp2_clm_confidence.R` (see also `exp2_clmm_confidence.ipynb` for the mixed-model attempt, which did not converge due to quasi-complete separation on `model`).

In [12]:
# ─────────────────────────────────────────────────────────────────────────────
# 10. Model 4 — Confidence (all trials)
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 4 — Confidence (all trials)"))
display(Markdown(
    "**Outcome:** `confidence_num` (1–6, Gaussian).  \n"
    "**Additional predictor:** `accuracy` (within-trial, 2-way with source_test).  \n"
    "**Covariates:** `rating_cen`, `order_c`, `model`."
))

_CONF_FE_INT = ("accuracy + source_test + setsize + fb_exp "
                "+ accuracy:source_test + source_test:setsize "
                "+ source_test:fb_exp + setsize:fb_exp "
                "+ model + order_c + rating_cen")
_CONF_FE_ADD = ("accuracy + source_test + setsize + fb_exp "
                "+ model + order_c + rating_cen")

CONF_INT_MAX = f"confidence_num ~ {_CONF_FE_INT} + (1 + source_test | trace)"
CONF_INT_RED = f"confidence_num ~ {_CONF_FE_INT} + (1 | trace)"

conf_cols = ["confidence_num","accuracy","source_test","setsize","fb_exp",
             "model","order_c","rating_cen","trace"]
conf_data = df[conf_cols].dropna()

models_conf = run_analysis_block(
    label           = "Confidence",
    int_f_max       = CONF_INT_MAX,
    int_f_red       = CONF_INT_RED,
    add_fe          = _CONF_FE_ADD,
    data            = conf_data,
    family          = "gaussian",
    prefix          = "conf",
    has_source_test = True,
    covariates      = ["rating_cen", "order_c", "accuracy"],
)

---
## Model 4 — Confidence (all trials)

**Outcome:** `confidence_num` (1–6, Gaussian).  
**Additional predictor:** `accuracy` (within-trial, 2-way with source_test).  
**Covariates:** `rating_cen`, `order_c`, `model`.

### Confidence — Step 1: RE structure selection

*Probing maximal RE `(1+source_test|trace)` — any isSingular warning below is expected at this step and will be handled automatically.*

[Confidence int-max] Fitting LMM: confidence_num ~ accuracy + source_test + setsize + fb_exp + accuracy:source_tes


**Confidence int-max — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,171488.373,171488.3846,171672.0614,0.6351,0.7305,0.2616,171448.373,0.6702,0.7025,71980,-85724.1865,72000,0.7025


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 6.76408e-06

[Confidence int-red] Fitting LMM: confidence_num ~ accuracy + source_test + setsize + fb_exp + accuracy:source_tes


**Confidence int-red — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,172101.4651,172101.4746,172266.7847,0.618,0.7173,0.2598,172065.4651,0.6953,0.7186,71982,-86032.7326,72000,0.7186


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 9.490504e-07



**Confidence RE: (1+source_test|trace) vs (1|trace) — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,172101.4651,172266.7847,-86032.7326,18.0,171961.4717,NaN,NaN,NaN,
1,171488.3730,171672.0614,-85724.1865,20.0,171345.8559,615.6158,2.0,0.0,***


*Confidence: Maximal RE non-singular → retained. LRT above tests whether the random slope improves fit.*

### Confidence — Step 2: Null & additive models

[Confidence null] Fitting LMM: confidence_num ~ 1 + (1 + source_test | trace)


**Confidence null — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,176374.5918,176374.5926,176420.5139,0.7152,0.7152,0.0,176364.5918,0.6822,0.7167,71995,-88182.2959,72000,0.7167


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 3.297831e-05

[Confidence additive] Fitting LMM: confidence_num ~ accuracy + source_test + setsize + fb_exp + model + order_c + r


**Confidence additive — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,173093.3541,173093.3616,173240.3048,0.6369,0.7227,0.2363,173061.3541,0.674,0.7081,71984,-86530.677,72000,0.7081


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 1.685115e-05



### Confidence — Step 2: Fixed-effect comparisons

**Confidence null → additive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,176374.5918,176420.5139,-88182.2959,5.0,176358.2126,NaN,NaN,NaN,
1,173093.3541,173240.3048,-86530.6770,16.0,172983.4210,3374.7915,11.0,0.0,***


**Confidence additive → interactive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,173093.3541,173240.3048,-86530.6770,16.0,172983.4210,NaN,NaN,NaN,
1,171488.3730,171672.0614,-85724.1865,20.0,171345.8559,1637.5651,4.0,0.0,***


### Confidence — Interactive model results

**Confidence — Fixed effects**

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value,sig
0,(Intercept),4.4488,0.0441,4.3624,4.5352,100.9781,5456.8408,0.0000,***
1,accuracy,0.2862,0.0092,0.2681,0.3043,31.0348,62407.3701,0.0000,***
2,source_testtest:imagined,0.3621,0.0156,0.3316,0.3927,23.2395,10451.0766,0.0000,***
3,setsize40,-0.0257,0.0391,-0.1024,0.0509,-0.6579,5114.8895,0.5106,
4,fb_expTrue,-0.1106,0.0394,-0.1878,-0.0334,-2.8093,5328.4500,0.0050,**
5,modelGemma3:12b-QAT,0.4135,0.0466,0.3221,0.5049,8.8703,4869.2938,0.0000,***
6,modelGemma3:27b,1.3848,0.0466,1.2934,1.4762,29.7064,4866.9747,0.0000,***
7,modelGemma3:27b-QAT,1.4449,0.0466,1.3535,1.5363,31.0057,4861.2119,0.0000,***
8,modelLlama4:16x17b,0.0994,0.0466,0.0080,0.1908,2.1314,4869.0316,0.0331,*
9,modelLlama3.3:70b,1.0190,0.0467,0.9275,1.1106,21.8231,4898.3999,0.0000,***


**Confidence — Type-III ANOVA (Satterthwaite)**

,model term,df1,df2,F_ratio,Chisq,p_value,sig
0,accuracy,1.0,inf,62.499,62.499,0.0000,***
1,source_test,1.0,inf,10.459,10.459,0.0012,**
2,setsize,1.0,inf,115.961,115.961,0.0000,***
3,fb_exp,1.0,inf,345.195,345.195,0.0000,***
4,model,5.0,inf,377.843,1889.215,0.0000,***
5,order_c,1.0,inf,0.815,0.815,0.3667,
6,rating_cen,1.0,inf,1249.950,1249.950,0.0000,***
7,accuracy:source_test,1.0,inf,1326.643,1326.643,0.0000,***
8,source_test:setsize,1.0,inf,3.390,3.390,0.0656,
9,source_test:fb_exp,1.0,inf,262.843,262.843,0.0000,***


**Confidence — VIF**

  ✓ All VIF < 5 


,term,vif,ci_increase_factor
0,accuracy,1.811,1.346
1,source_testtest:imagined,4.620,2.149
2,setsize40,2.752,1.659
3,fb_expTrue,3.235,1.799
4,modelGemma3:12b-QAT,1.497,1.224
5,modelGemma3:27b,1.360,1.166
6,modelGemma3:27b-QAT,1.355,1.164
7,modelLlama4:16x17b,1.251,1.118
8,modelLlama3_3:70b,1.426,1.194
9,order_c,1.003,1.002


### Confidence — Diagnostics

  [LMM diagnostics skipped for large Gaussian model — results unaffected]


### Confidence — Post-hoc contrasts

**Confidence | source_test (H1) — Pairwise emmeans: source_test [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,test:perceived - test:imagined,-0.0242,0.0075,inf,-0.0389,-0.0095,-3.2341,0.0012,***


**Confidence | fb_exp (H2) — Pairwise emmeans: fb_exp [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,False - True,0.5023,0.027,inf,0.4493,0.5553,18.5794,0.0,


**Confidence | source_test × fb_exp (H3) — Pairwise emmeans: source_test | fb_exp [fdr]**

  [emmeans — '<' not supported between instances of 'str' and 'float']


**Confidence | fb_exp × source_test (H3) — Pairwise emmeans: fb_exp | source_test [fdr]**

,contrast,source_test,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,False - True,test:perceived,0.3884,0.0285,inf,0.3326,0.4442,13.6411,0.0,
1,False - True,test:imagined,0.6161,0.0274,inf,0.5625,0.6698,22.5046,0.0,


**Confidence | setsize — Pairwise emmeans: setsize [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,setsize20 - setsize40,0.2906,0.027,inf,0.2377,0.3435,10.7685,0.0,


**Confidence | model (H4) — Pairwise emmeans: model [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,Gemma3:12b - (Gemma3:12b-QAT),-0.4135,0.0466,inf,-0.5504,-0.2767,-8.8703,0.0000,***
1,Gemma3:12b - Gemma3:27b,-1.3848,0.0466,inf,-1.5216,-1.2480,-29.7064,0.0000,***
2,Gemma3:12b - (Gemma3:27b-QAT),-1.4449,0.0466,inf,-1.5817,-1.3081,-31.0057,0.0000,***
3,Gemma3:12b - Llama4:16x17b,-0.0994,0.0466,inf,-0.2362,0.0375,-2.1314,0.0354,***
4,Gemma3:12b - Llama3.3:70b,-1.0190,0.0467,inf,-1.1561,-0.8820,-21.8231,0.0000,***
5,(Gemma3:12b-QAT) - Gemma3:27b,-0.9712,0.0466,inf,-1.1081,-0.8344,-20.8272,0.0000,***
6,(Gemma3:12b-QAT) - (Gemma3:27b-QAT),-1.0314,0.0466,inf,-1.1682,-0.8945,-22.1146,0.0000,***
7,(Gemma3:12b-QAT) - Llama4:16x17b,0.3142,0.0466,inf,0.1774,0.4510,6.7412,0.0000,
8,(Gemma3:12b-QAT) - Llama3.3:70b,-0.6055,0.0467,inf,-0.7425,-0.4685,-12.9718,0.0000,***
9,Gemma3:27b - (Gemma3:27b-QAT),-0.0601,0.0466,inf,-0.1969,0.0767,-1.2901,0.1970,***


**Confidence — Covariate slopes**

*Covariate: `rating_cen`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
11,rating_cen,0.0056,0.0002,0.0053,0.0059,35.3546,67274.6181,0.0


*Covariate: `order_c`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
10,order_c,0.0243,0.0269,-0.0285,0.077,0.9026,4858.4905,0.3668


*Covariate: `accuracy`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
1,accuracy,0.2862,0.0092,0.2681,0.3043,31.0348,62407.3701,0.0
12,accuracy:source_testtest:imagined,-0.4739,0.0130,-0.4994,-0.4484,-36.4231,67778.7220,0.0


## Section 11: Model 4P — Confidence, perceived + read_hallucination

> **Note (2026-06-14):** This Gaussian LMM analysis of Confidence is exploratory and is **not** the model reported in `main.tex`. The Confidence results reported in the manuscript come from the ordinal Cumulative Link Model fit separately in `notebooks/04_exp2/exp2_clm_confidence.R` (see also `exp2_clmm_confidence.ipynb` for the mixed-model attempt, which did not converge due to quasi-complete separation on `model`).

In [13]:
# ─────────────────────────────────────────────────────────────────────────────
# 11. Model 4P — Confidence, perceived + read_hallucination
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 4P — Confidence (perceived + read_hallucination)"))

_CONF_P_FE_INT = ("accuracy + setsize * fb_exp "
                  "+ model + order_c + rating_cen + read_hallucination")
_CONF_P_FE_ADD = ("accuracy + setsize + fb_exp "
                  "+ model + order_c + rating_cen + read_hallucination")
CONF_P_INT     = f"confidence_num ~ {_CONF_P_FE_INT} + (1 | trace)"

conf_p_cols = ["confidence_num","accuracy","setsize","fb_exp",
               "model","order_c","rating_cen","read_hallucination","trace"]
conf_p_data = df_perc[conf_p_cols].dropna()

models_conf_p = run_analysis_block(
    label           = "Confidence (perceived)",
    int_f_max       = CONF_P_INT,
    int_f_red       = CONF_P_INT,
    add_fe          = _CONF_P_FE_ADD,
    data            = conf_p_data,
    family          = "gaussian",
    prefix          = "conf_p",
    has_source_test = False,
    covariates      = ["rating_cen", "order_c", "accuracy", "read_hallucination"],
)

---
## Model 4P — Confidence (perceived + read_hallucination)

### Confidence (perceived) — Step 1: RE structure selection

[Confidence (perceived) interactive] Fitting LMM: confidence_num ~ accuracy + setsize * fb_exp + model + order_c + rating_cen + re


**Confidence (perceived) interactive — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,92538.163,92538.1764,92665.5322,0.6223,0.7129,0.24,92508.163,0.6909,0.7375,35985,-46254.0815,36000,0.7375


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 2.989267e-07



*Single RE structure (source_test constant) — no RE comparison.*

### Confidence (perceived) — Step 2: Null & additive models

[Confidence (perceived) null] Fitting LMM: confidence_num ~ 1 + (1 | trace)


**Confidence (perceived) null — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,95821.6233,95821.624,95847.0971,0.6948,0.6948,0.0,95815.6233,0.7085,0.7575,35997,-47907.8117,36000,0.7575


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 6.7631e-07

[Confidence (perceived) additive] Fitting LMM: confidence_num ~ accuracy + setsize + fb_exp + model + order_c + rating_cen + re


**Confidence (perceived) additive — Fit statistics**

,AIC,AICc,BIC,ICC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,92595.7399,92595.7516,92714.6177,0.6256,0.7108,0.2276,92567.7399,0.6908,0.7375,35986,-46283.8699,36000,0.7375


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 8.454384e-08



### Confidence (perceived) — Step 2: Fixed-effect comparisons

**Confidence (perceived) null → additive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,95821.6233,95847.0971,-47907.8117,3.0,95809.3153,NaN,NaN,NaN,
1,92595.7399,92714.6177,-46283.8699,14.0,92493.0050,3316.3104,11.0,0.0,***


**Confidence (perceived) additive → interactive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,92595.7399,92714.6177,-46283.8699,14.0,92493.0050,NaN,NaN,NaN,
1,92538.1630,92665.5322,-46254.0815,15.0,92429.4215,63.5835,1.0,0.0,***


### Confidence (perceived) — Interactive model results

**Confidence (perceived) — Fixed effects**

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value,sig
0,(Intercept),4.4440,0.0462,4.3535,4.5345,96.2316,5366.1242,0.0000,***
1,accuracy,0.2600,0.0103,0.2397,0.2802,25.1684,33455.8285,0.0000,***
2,setsize40,-0.0763,0.0404,-0.1554,0.0029,-1.8882,4919.5918,0.0591,
3,fb_expTrue,-0.1745,0.0411,-0.2551,-0.0939,-4.2420,5288.0469,0.0000,***
4,modelGemma3:12b-QAT,0.4693,0.0495,0.3722,0.5664,9.4760,4935.9322,0.0000,***
5,modelGemma3:27b,1.3929,0.0495,1.2959,1.4899,28.1504,4919.3305,0.0000,***
6,modelGemma3:27b-QAT,1.4631,0.0495,1.3661,1.5601,29.5672,4919.8200,0.0000,***
7,modelLlama4:16x17b,0.1713,0.0496,0.0741,0.2685,3.4540,4961.9386,0.0006,***
8,modelLlama3.3:70b,1.2313,0.0502,1.1330,1.3297,24.5527,5176.8949,0.0000,***
9,order_c,0.0125,0.0285,-0.0435,0.0684,0.4368,4900.6115,0.6623,


**Confidence (perceived) — Type-III ANOVA (Satterthwaite)**

,model term,df1,df2,F_ratio,Chisq,p_value,sig
0,accuracy,1.0,inf,633.448,633.448,0.0000,***
1,setsize,1.0,inf,113.420,113.420,0.0000,***
2,fb_exp,1.0,inf,194.439,194.439,0.0000,***
3,model,5.0,inf,343.069,1715.345,0.0000,***
4,order_c,1.0,inf,0.191,0.191,0.6623,
5,rating_cen,1.0,inf,926.095,926.095,0.0000,***
6,read_hallucination,1.0,inf,0.000,0.000,0.9901,
7,setsize:fb_exp,1.0,inf,63.868,63.868,0.0000,***


**Confidence (perceived) — VIF**

  ✓ All VIF < 5 


,term,vif,ci_increase_factor
0,accuracy,1.027,1.013
1,setsize40,1.966,1.402
2,fb_expTrue,2.513,1.585
3,modelGemma3:12b-QAT,1.455,1.206
4,modelGemma3:27b,1.339,1.157
5,modelGemma3:27b-QAT,1.350,1.162
6,modelLlama4:16x17b,1.304,1.142
7,modelLlama3_3:70b,1.567,1.252
8,order_c,1.004,1.002
9,rating_cen,1.102,1.050


### Confidence (perceived) — Diagnostics

  [LMM diagnostics skipped for large Gaussian model — results unaffected]


### Confidence (perceived) — Post-hoc contrasts

**Confidence (perceived) | fb_exp (H2) — Pairwise emmeans: fb_exp [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,False - True,0.4026,0.0289,inf,0.346,0.4592,13.9442,0.0,


**Confidence (perceived) | setsize — Pairwise emmeans: setsize [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,setsize20 - setsize40,0.3044,0.0286,inf,0.2484,0.3604,10.6499,0.0,


**Confidence (perceived) | model (H4) — Pairwise emmeans: model [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,Gemma3:12b - (Gemma3:12b-QAT),-0.4693,0.0495,inf,-0.6147,-0.3239,-9.4760,0.0000,***
1,Gemma3:12b - Gemma3:27b,-1.3929,0.0495,inf,-1.5381,-1.2476,-28.1504,0.0000,***
2,Gemma3:12b - (Gemma3:27b-QAT),-1.4631,0.0495,inf,-1.6083,-1.3178,-29.5672,0.0000,***
3,Gemma3:12b - Llama4:16x17b,-0.1713,0.0496,inf,-0.3169,-0.0257,-3.4540,0.0006,***
4,Gemma3:12b - Llama3.3:70b,-1.2313,0.0502,inf,-1.3785,-1.0841,-24.5527,0.0000,***
5,(Gemma3:12b-QAT) - Gemma3:27b,-0.9236,0.0497,inf,-1.0696,-0.7776,-18.5720,0.0000,***
6,(Gemma3:12b-QAT) - (Gemma3:27b-QAT),-0.9938,0.0497,inf,-1.1398,-0.8478,-19.9783,0.0000,***
7,(Gemma3:12b-QAT) - Llama4:16x17b,0.2980,0.0499,inf,0.1515,0.4445,5.9716,0.0000,
8,(Gemma3:12b-QAT) - Llama3.3:70b,-0.7620,0.0508,inf,-0.9111,-0.6130,-15.0053,0.0000,***
9,Gemma3:27b - (Gemma3:27b-QAT),-0.0702,0.0494,inf,-0.2153,0.0749,-1.4200,0.1556,***


**Confidence (perceived) — Covariate slopes**

*Covariate: `rating_cen`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
10,rating_cen,0.0056,0.0002,0.0053,0.006,30.4318,32327.026,0.0


*Covariate: `order_c`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
9,order_c,0.0125,0.0285,-0.0435,0.0684,0.4368,4900.6115,0.6623


*Covariate: `accuracy`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
1,accuracy,0.26,0.0103,0.2397,0.2802,25.1684,33455.8285,0.0


*Covariate: `read_hallucination`*

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value
11,read_hallucination,0.0001,0.0115,-0.0223,0.0226,0.0124,33461.6533,0.9901


## Section 12: Model 5 — Metacognitive γ (all trials)

In [ ]:
# ─────────────────────────────────────────────────────────────────────────────
# 12. Model 5 — Metacognitive γ (trace-level, all trials)
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 5 — Metacognitive Sensitivity γ (all trials)"))
display(Markdown(
    "γ (Goodman–Kruskal) computed per `trace × source_test`, Fisher-Z transformed.  \n"
    "**Covariates:** `model` only — `rating_cen` and `order_c` are trial-level.  \n"
    "**RE:** `(1|trace)` only. γ is aggregated at the trace×source level, giving "
    "exactly **2 rows per trace cluster**. A random slope for `source_test` is "
    "structurally unidentifiable with only 2 obs/cluster and will always be singular."
))

df_gamma_src = gamma_mod.calculate_gamma_across_groups(
    df, [sim_id] + grp_between + grp_within
)
df_gamma_src["f_gamma"] = fisher_z(df_gamma_src["gamma"])

_GAM_FE_INT = ("source_test + setsize + fb_exp "
               "+ source_test:setsize + source_test:fb_exp + setsize:fb_exp + model")
_GAM_FE_ADD = "source_test + setsize + fb_exp + model"

# Gamma is computed per trace × source_test → exactly 2 rows per trace cluster.
# A random slope for source_test is structurally unidentifiable with only 2 obs/cluster.
# Use (1|trace) throughout; setting MAX=RED bypasses the unnecessary singular fit.
GAM_INT_MAX = f"f_gamma ~ {_GAM_FE_INT} + (1 | trace)"
GAM_INT_RED = f"f_gamma ~ {_GAM_FE_INT} + (1 | trace)"

gamma_fit = df_gamma_src.copy()
if "trace" not in gamma_fit.columns and sim_id in gamma_fit.columns:
    gamma_fit = gamma_fit.rename(columns={sim_id: "trace"})
for col in ["setsize","fb_exp","model","source_test"]:
    if col in gamma_fit.columns:
        gamma_fit[col] = gamma_fit[col].astype(str)
gamma_data = gamma_fit[["f_gamma","source_test","setsize","fb_exp","model","trace"]].dropna()

models_gam = run_analysis_block(
    label           = "Metacognitive γ",
    int_f_max       = GAM_INT_MAX,
    int_f_red       = GAM_INT_RED,
    add_fe          = _GAM_FE_ADD,
    data            = gamma_data,
    family          = "gaussian",
    prefix          = "gamma",
    has_source_test = True,
    covariates      = [],   # model handled by pairwise; no continuous covariates
)

---
## Model 5 — Metacognitive Sensitivity γ (all trials)

γ (Goodman–Kruskal) computed per `trace × source_test`, Fisher-Z transformed.  
**Covariates:** `model` only — `rating_cen` and `order_c` are trial-level.  
**RE:** `(1|trace)` only. γ is aggregated at the trace×source level, giving exactly **2 rows per trace cluster**. A random slope for `source_test` is structurally unidentifiable with only 2 obs/cluster and will always be singular.

### Metacognitive γ — Step 1: RE structure selection

[Metacognitive γ interactive] Fitting LMM: f_gamma ~ source_test + setsize + fb_exp + source_test:setsize + source_test:fb_
R messages: 
boundary (singular) fit: see help('isSingular')

Random effect variances not available. Returned R2 does not account for random effects.

R messages: 
boundary (singular) fit: see help('isSingular')

Random effect variances not available. Returned R2 does not account for random effects.



**Metacognitive γ interactive — Fit statistics**

,AIC,AICc,BIC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,24436.7957,24436.8913,24526.2785,-2147483648,0.2861,24408.7957,3.8421,3.8474,4396,-12204.3979,4410,3.8474


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 0



*Single RE structure (source_test constant) — no RE comparison.*

### Metacognitive γ — Step 2: Null & additive models

[Metacognitive γ null] Fitting LMM: f_gamma ~ 1 + (1 | trace)
R messages: 
boundary (singular) fit: see help('isSingular')

Random effect variances not available. Returned R2 does not account for random effects.

R messages: 
boundary (singular) fit: see help('isSingular')

Random effect variances not available. Returned R2 does not account for random effects.



**Metacognitive γ null — Fit statistics**

,AIC,AICc,BIC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,25886.1355,25886.141,25905.3104,-2147483648,0.0,25880.1355,4.549,4.5496,4407,-12940.0678,4410,4.5496


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 0

[Metacognitive γ additive] Fitting LMM: f_gamma ~ source_test + setsize + fb_exp + model + (1 | trace)
R messages: 
boundary (singular) fit: see help('isSingular')

Random effect variances not available. Returned R2 does not account for random effects.

R messages: 
boundary (singular) fit: see help('isSingular')

Random effect variances not available. Returned R2 does not account for random effects.



**Metacognitive γ additive — Fit statistics**

,AIC,AICc,BIC,R2_conditional,R2_marginal,REMLcrit,RMSE,Sigma,df_residual,logLik,nobs,sigma
0,24782.5594,24782.6194,24852.8673,-2147483648,0.2264,24760.5594,4.0002,4.0043,4399,-12380.2797,4410,4.0043


  convergence_status: Convergence status
: [1] TRUE
attr(,"gradient")
[1] 0



### Metacognitive γ — Step 2: Fixed-effect comparisons

**Metacognitive γ null → additive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,25886.1355,25905.3104,-12940.0678,3.0,25876.6117,NaN,NaN,NaN,
1,24782.5594,24852.8673,-12380.2797,11.0,24742.6278,1133.9839,8.0,0.0,***


**Metacognitive γ additive → interactive — LRT**

,AIC,BIC,logLik,npar,-2*log(L),Chisq,Df,Pr(>Chisq),sig
0,24782.5594,24852.8673,-12380.2797,11.0,24742.6278,NaN,NaN,NaN,
1,24436.7957,24526.2785,-12204.3979,14.0,24386.9859,355.6418,3.0,0.0,***


### Metacognitive γ — Interactive model results

**Metacognitive γ — Fixed effects**

,term,estimate,std_error,conf_low,conf_high,t_stat,df,p_value,sig
0,(Intercept),4.5314,0.2204,4.0993,4.9636,20.5567,4398.0,0.0000,***
1,source_testtest:imagined,-6.1965,0.2181,-6.6240,-5.7689,-28.4113,4398.0,0.0000,***
2,setsize40,0.5087,0.2214,0.0747,0.9428,2.2977,4398.0,0.0216,*
3,fb_expTrue,-3.2240,0.2128,-3.6412,-2.8068,-15.1514,4398.0,0.0000,***
4,modelGemma3:12b-QAT,-0.7246,0.1870,-1.0913,-0.3579,-3.8744,4398.0,0.0001,***
5,modelGemma3:27b,-1.8360,0.2298,-2.2865,-1.3856,-7.9908,4398.0,0.0000,***
6,modelGemma3:27b-QAT,-3.4336,0.3316,-4.0837,-2.7835,-10.3549,4398.0,0.0000,***
7,modelLlama4:16x17b,-1.8070,0.1780,-2.1559,-1.4581,-10.1524,4398.0,0.0000,***
8,modelLlama3.3:70b,-1.8689,0.1988,-2.2586,-1.4791,-9.4007,4398.0,0.0000,***
9,source_testtest:imagined:setsize40,-0.5919,0.2337,-1.0500,-0.1337,-2.5327,4398.0,0.0114,*


**Metacognitive γ — Type-III ANOVA (Satterthwaite)**

,model term,df1,df2,F_ratio,Chisq,p_value,sig
0,source_test,1.0,inf,1316.889,1316.889,0.0000,***
1,setsize,1.0,inf,19.516,19.516,0.0000,***
2,fb_exp,1.0,inf,30.437,30.437,0.0000,***
3,model,5.0,inf,41.426,207.130,0.0000,***
4,source_test:setsize,1.0,inf,6.414,6.414,0.0113,*
5,source_test:fb_exp,1.0,inf,353.690,353.690,0.0000,***
6,setsize:fb_exp,1.0,inf,7.803,7.803,0.0052,**


**Metacognitive γ — VIF**

  ✓ All VIF < 5 


,term,vif,ci_increase_factor
0,source_testtest:imagined,3.170,1.781
1,setsize40,2.921,1.709
2,fb_expTrue,2.915,1.707
3,modelGemma3:12b-QAT,1.652,1.285
4,modelGemma3:27b,1.652,1.285
5,modelGemma3:27b-QAT,1.565,1.251
6,modelLlama4:16x17b,1.652,1.285
7,modelLlama3_3:70b,1.652,1.285
8,source_testtest:imagined:setsize40,2.923,1.710
9,source_testtest:imagined:fb_expTrue,3.154,1.776


### Metacognitive γ — Diagnostics

  [LMM diagnostics skipped for large Gaussian model — results unaffected]


### Metacognitive γ — Post-hoc contrasts

**Metacognitive γ | source_test (H1) — Pairwise emmeans: source_test [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,test:perceived - test:imagined,4.2761,0.1178,inf,4.0452,4.5071,36.289,0.0,


**Metacognitive γ | fb_exp (H2) — Pairwise emmeans: fb_exp [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,False - True,0.6743,0.1222,inf,0.4348,0.9139,5.517,0.0,


**Metacognitive γ | source_test × fb_exp (H3) — Pairwise emmeans: source_test | fb_exp [fdr]**

  [emmeans — '<' not supported between instances of 'str' and 'float']


**Metacognitive γ | fb_exp × source_test (H3) — Pairwise emmeans: fb_exp | source_test [fdr]**

,contrast,source_test,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,False - True,test:perceived,2.8906,0.1723,inf,2.5530,3.2282,16.7800,0.0,
1,False - True,test:imagined,-1.5420,0.1673,inf,-1.8698,-1.2141,-9.2186,0.0,***


**Metacognitive γ | setsize — Pairwise emmeans: setsize [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,setsize20 - setsize40,-0.5462,0.1236,inf,-0.7885,-0.3039,-4.4177,0.0,***


**Metacognitive γ | model (H4) — Pairwise emmeans: model [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,Gemma3:12b - (Gemma3:12b-QAT),0.7246,0.1870,inf,0.1757,1.2736,3.8744,0.0001,
1,Gemma3:12b - Gemma3:27b,1.8360,0.2298,inf,1.1616,2.5105,7.9908,0.0000,
2,Gemma3:12b - (Gemma3:27b-QAT),3.4336,0.3316,inf,2.4603,4.4069,10.3549,0.0000,
3,Gemma3:12b - Llama4:16x17b,1.8070,0.1780,inf,1.2846,2.3294,10.1524,0.0000,
4,Gemma3:12b - Llama3.3:70b,1.8689,0.1988,inf,1.2854,2.4524,9.4007,0.0000,
5,(Gemma3:12b-QAT) - Gemma3:27b,1.1114,0.2179,inf,0.4717,1.7511,5.0996,0.0000,
6,(Gemma3:12b-QAT) - (Gemma3:27b-QAT),2.7090,0.3282,inf,1.7458,3.6722,8.2550,0.0000,
7,(Gemma3:12b-QAT) - Llama4:16x17b,1.0824,0.1678,inf,0.5898,1.5750,6.4491,0.0000,
8,(Gemma3:12b-QAT) - Llama3.3:70b,1.1443,0.1921,inf,0.5803,1.7082,5.9553,0.0000,
9,Gemma3:27b - (Gemma3:27b-QAT),1.5975,0.3570,inf,0.5497,2.6453,4.4752,0.0000,


In [ ]:
# ─────────────────────────────────────────────────────────────────────────────
# 12b. Exclusion pattern for Model 5 (manuscript Results, Metacognitive
#      Sensitivity paragraph) — is gamma-undefined status itself associated
#      with model/setsize/fb_exp/source_test?
#
#      NOTE: a full logistic regression on "excluded" is NOT fit here.
#      Gemma3:27b-QAT / no-feedback / imagined-source is deterministic
#      (400/400 traces excluded = 100%), which causes perfect separation
#      for that model x condition combination -- the same pathology
#      already flagged for Gemma3:27b-QAT's quasi-complete separation in
#      the Experiment 1 accuracy GLM (see Methods). A chi-square test of
#      independence is used instead, since it does not require converging
#      a model through a deterministic cell.
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## 12b. Exclusion Pattern (chi-square test, manuscript text check)"))

from scipy import stats

g_excl = df_gamma_src if "df_gamma_src" in dir() else None
gamma_fit_check = gamma_mod.calculate_gamma_across_groups(
    df, [sim_id] + grp_between + grp_within
)
gamma_fit_check["excluded"] = gamma_fit_check["gamma"].isna().astype(int)

ct = pd.crosstab(
    [gamma_fit_check["model"], gamma_fit_check["setsize"],
     gamma_fit_check["fb_exp"], gamma_fit_check["source_test"]],
    gamma_fit_check["excluded"],
)
chi2, p, dof, _ = stats.chi2_contingency(ct)
print(f"Omnibus chi-square (excluded ~ 24-cell condition): "
      f"chi2({dof}) = {chi2:.2f}, p = {p:.3e}")
print()

rate = (gamma_fit_check.groupby(["model", "fb_exp", "source_test"], observed=True)["excluded"]
        .mean() * 100).round(1)
print("Exclusion rate (%) by model x feedback x source, top 8:")
print(rate.sort_values(ascending=False).head(8))
print()

sub = gamma_fit_check[(gamma_fit_check["model"] == "Gemma3:27b-QAT")
                       & (gamma_fit_check["fb_exp"] == "False")
                       & (gamma_fit_check["source_test"] == "test:imagined")]
print("Gemma3:27b-QAT / no-feedback / imagined-source, excluded value counts:")
print(sub["excluded"].value_counts())

---
## 12b. Exclusion Pattern (chi-square test, manuscript text check)

Omnibus chi-square (excluded ~ 24-cell condition): chi2(47) = 3489.06, p = 0.000e+00

Exclusion rate (%) by model x feedback x source, top 8:
model           fb_exp  source_test
Gemma3:27b-QAT  False   test:imagined     100.0
                        test:perceived     99.2
                True    test:imagined      84.8
Gemma3:27b      True    test:perceived     81.2
Gemma3:12b      False   test:perceived     77.5
Gemma3:27b      True    test:imagined      76.2
Gemma3:27b-QAT  True    test:perceived     73.0
Gemma3:27b      False   test:perceived     68.5
Name: excluded, dtype: float64

Gemma3:27b-QAT / no-feedback / imagined-source, excluded value counts:
excluded
1    400
Name: count, dtype: int64


### Manuscript cross-reference — Gamma LMM source contrast

The output block above (Model 5 — Metacognitive γ) already computes
the emmeans source contrast. The key value reported in `main.tex` is:

```
test:perceived - test:imagined  estimate = 4.276  SE = 0.118  CI = [4.045, 4.507]  z = 36.29  p < .001
```

Reported in text as: pairwise contrast perceived − imagined = 4.28, SE = 0.12, p < .001

This appears in the cell above under **'Pairwise source contrast (source_test)'**.
The standalone call below reproduces it explicitly if re-running.

In [19]:
# Explicit source contrast — Gamma LMM (manuscript main.tex §Experiment 2 Metacognition)
# Reported in text: perceived - imagined = 4.28, SE = 0.12, p < .001
# Run this cell only after models_gamma has been fitted in Cell 25 above.

import rpy2.robjects as ro
ro.globalenv['gamma_int'] = models_gam['interactive'].r_model
ro.r("""
library(emmeans)
em_src_gam <- emmeans(gamma_int, ~ source_test)
cat('\n=== Gamma LMM: source emmeans contrast (perceived - imagined) ===\n')
print(contrast(em_src_gam, method = 'pairwise'))
""")


In [24]:
# Explicit source contrast — Gamma LMM (manuscript main.tex §Experiment 2 Metacognition)
# Reported in text: perceived - imagined = 4.28, SE = 0.12, p < .001
pairwise(models_gam['interactive'], 'source_test', label='Gamma LMM — source contrast')

**Gamma LMM — source contrast — Pairwise emmeans: source_test [fdr]**

,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,test:perceived - test:imagined,4.2761,0.1178,inf,4.0452,4.5071,36.289,0.0,


,contrast,estimate,SE,df,asymp_LCL,asymp_UCL,z_ratio,p_value,sig
0,test:perceived - test:imagined,4.276107,0.117835,inf,4.045155,4.50706,36.288971,2.415072e-288,


## Section 13: Model 5P — γ, perceived + rh_mean

In [20]:
# ─────────────────────────────────────────────────────────────────────────────
# 13. Model 5P — γ, perceived trials + rh_mean (trace-level)
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## Model 5P — Metacognitive γ (perceived + rh_mean)"))
display(Markdown(
    "γ computed on perceived-only trials per trace.  \n"
    "`rh_mean` = mean RH rate per trace (perceived trials) — between-trace covariate."
))

df_gamma_perc = gamma_mod.calculate_gamma_across_groups(
    df_perc, [sim_id] + grp_between
)
df_gamma_perc["f_gamma"] = fisher_z(df_gamma_perc["gamma"])

rh_trace = (
    df_perc.groupby(sim_id, observed=True)["read_hallucination"]
    .mean().reset_index()
    .rename(columns={"read_hallucination": "rh_mean"})
)
gamma_perc_fit = df_gamma_perc.copy()
if "trace" not in gamma_perc_fit.columns and sim_id in gamma_perc_fit.columns:
    gamma_perc_fit = gamma_perc_fit.rename(columns={sim_id: "trace"})
gamma_perc_fit = gamma_perc_fit.merge(rh_trace, on="trace", how="left")
for col in ["setsize","fb_exp","model"]:
    if col in gamma_perc_fit.columns:
        gamma_perc_fit[col] = gamma_perc_fit[col].astype(str)
gp_data = gamma_perc_fit[["f_gamma","setsize","fb_exp","model","rh_mean","trace"]].dropna()

_GAM_P_FE_INT = "setsize * fb_exp + model + rh_mean"
_GAM_P_FE_ADD = "setsize + fb_exp + model + rh_mean"

# γ (perceived) has ONE row per trace → (1|trace) is impossible (n_levels = n_obs).
# Use OLS (statsmodels) instead of lmer for this trace-level aggregated outcome.
display(Markdown("### γ (perceived) — OLS (trace-level aggregated, no RE)"))
import statsmodels.formula.api as smf

gp_data_ols = gp_data.copy()
# Ensure categoricals are strings for patsy
for col in ["setsize","fb_exp","model"]:
    gp_data_ols[col] = gp_data_ols[col].astype(str)

_gp_int_formula = f"f_gamma ~ {_GAM_P_FE_INT}"
_gp_add_formula = f"f_gamma ~ {_GAM_P_FE_ADD}"
_gp_nul_formula = "f_gamma ~ 1"

ols_int = smf.ols(_gp_int_formula, data=gp_data_ols).fit()
ols_add = smf.ols(_gp_add_formula, data=gp_data_ols).fit()
ols_nul = smf.ols(_gp_nul_formula, data=gp_data_ols).fit()

display(Markdown("**γ (perceived) — Null vs Additive (F-test)**"))
from scipy.stats import f as f_dist
def ols_lrt(m_red, m_full, label=""):
    df_diff = m_full.df_model - m_red.df_model
    f_stat  = ((m_red.ssr - m_full.ssr) / df_diff) / (m_full.ssr / m_full.df_resid)
    p_val   = 1 - f_dist.cdf(f_stat, df_diff, m_full.df_resid)
    sig = "***" if p_val < .001 else "**" if p_val < .01 else "*" if p_val < .05 else ""
    print(f"  {label}: F({int(df_diff)},{int(m_full.df_resid)})={f_stat:.3f}  p={p_val:.4e}  {sig}")
    print(f"  AIC null={m_red.aic:.1f}  AIC full={m_full.aic:.1f}")

ols_lrt(ols_nul, ols_add, "Null → Additive")
ols_lrt(ols_add, ols_int, "Additive → Interactive")

display(Markdown("**γ (perceived) — Interactive model coefficients**"))
coef_df = pd.DataFrame({
    "term":      ols_int.params.index,
    "estimate":  ols_int.params.values,
    "std_error": ols_int.bse.values,
    "t_stat":    ols_int.tvalues.values,
    "p_value":   ols_int.pvalues.values,
})
coef_df["sig"] = coef_df["p_value"].map(
    lambda p: "***" if p < .001 else "**" if p < .01 else "*" if p < .05 else "")
display(coef_df.round(4))
print(f"  R²={ols_int.rsquared:.4f}  Adj-R²={ols_int.rsquared_adj:.4f}  n={int(ols_int.nobs)}")

# Wrap in a dict so the summary table code doesn't crash
models_gam_p = {"null": None, "additive": None, "interactive": None, "int_reduced": None}

---
## Model 5P — Metacognitive γ (perceived + rh_mean)

γ computed on perceived-only trials per trace.  
`rh_mean` = mean RH rate per trace (perceived trials) — between-trace covariate.

### γ (perceived) — OLS (trace-level aggregated, no RE)

**γ (perceived) — Null vs Additive (F-test)**

  Null → Additive: F(8,2174)=66.465  p=1.1102e-16  ***
  AIC null=12451.0  AIC full=11989.3
  Additive → Interactive: F(1,2173)=34.099  p=6.0247e-09  ***
  AIC null=11989.3  AIC full=11957.3


**γ (perceived) — Interactive model coefficients**

,term,estimate,std_error,t_stat,p_value,sig
0,Intercept,2.3040,0.3366,6.8452,0.0000,***
1,setsize[T.40],-1.1141,0.2660,-4.1889,0.0000,***
2,fb_exp[T.True],-3.9855,0.2471,-16.1277,0.0000,***
3,model[T.Gemma3:12b-QAT],0.4155,0.2672,1.5553,0.1200,
4,model[T.Gemma3:27b],0.8412,0.3595,2.3400,0.0194,*
5,model[T.Gemma3:27b-QAT],-1.7946,0.4149,-4.3255,0.0000,***
6,model[T.Llama3.3:70b],3.1395,0.3716,8.4489,0.0000,***
7,model[T.Llama4:16x17b],1.9641,0.2919,6.7281,0.0000,***
8,setsize[T.40]:fb_exp[T.True],1.9720,0.3377,5.8395,0.0000,***
9,rh_mean,1.5486,0.3861,4.0112,0.0001,***


  R²=0.2089  Adj-R²=0.2057  n=2183


## Section 14: Model Comparison Summary Table

In [21]:
# ─────────────────────────────────────────────────────────────────────────────
# 14. Model comparison summary table
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## 14. Model Comparison Summary"))

_all_models = [
    ("1.  RH (perceived)",      models_rh),
    ("2.  Accuracy",            models_acc),
    ("2P. Accuracy (perceived)", models_acc_p),
    ("3.  Rating",              models_rr),
    ("3P. Rating (perceived)",  models_rr_p),
    ("4.  Confidence",          models_conf),
    ("4P. Confidence (perc.)",  models_conf_p),
    ("5.  γ (all)",             models_gam),
    ("5P. γ (perceived)",       models_gam_p),
]

rows = []
for name, md in _all_models:
    for mtype in ("null", "additive", "interactive"):
        m = md.get(mtype)
        if m is None:
            continue
        rows.append({
            "Outcome":    name,
            "Model":      mtype,
            "AIC":        round(_aic(m), 1) if not np.isnan(_aic(m)) else "—",
            "BIC":        round(_bic(m), 1) if not np.isnan(_bic(m)) else "—",
            "n":          len(m.data) if hasattr(m, "data") and m.data is not None else "—",
        })

display(pd.DataFrame(rows))

---
## 14. Model Comparison Summary

,Outcome,Model,AIC,BIC,n
0,1. RH (perceived),null,37216.3,37233.3,36000
1,1. RH (perceived),additive,32966.1,33051.0,36000
2,1. RH (perceived),interactive,32947.4,33040.8,36000
3,2. Accuracy,null,98026.1,98044.5,72000
4,2. Accuracy,additive,93145.0,93255.2,72000
5,2. Accuracy,interactive,90282.8,90420.5,72000
6,2P. Accuracy (perceived),null,40906.5,40923.5,36000
7,2P. Accuracy (perceived),additive,39059.1,39161.0,36000
8,2P. Accuracy (perceived),interactive,39061.4,39171.8,36000
9,3. Rating,null,633845.1,633872.6,72000


## Section 15: Key Results Figure (6-panel)

In [22]:
# ─────────────────────────────────────────────────────────────────────────────
# 15. Key Results Figure (6-panel)
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## 15. Key Results Figure"))

MODEL_ORDER  = sorted(df["model"].astype(str).unique())
MODEL_LABELS = [m.replace("-", "-\n") for m in MODEL_ORDER]
FB_VALS      = ["True", "False"]
FB_LABELS    = {"True": "Feedback Present", "False": "Feedback Absent"}
x, bar_w     = np.arange(len(MODEL_ORDER)), 0.38

df_gamma_sim = gamma_mod.calculate_gamma_across_groups(df, [sim_id] + grp_between)
df_gamma_sim["f_gamma"] = fisher_z(df_gamma_sim["gamma"])

rh_means   = df_perc.groupby(["model","fb_exp"], observed=True)["read_hallucination"].mean().to_dict()
acc_means  = df.groupby(["model","fb_exp"],      observed=True)["accuracy"].mean().to_dict()
src_cats   = df["source_test"].unique().tolist()
perc_src   = next(s for s in src_cats if "perceived" in s)
gam_all_d  = df_gamma_sim.groupby(["model","fb_exp"], observed=True)["f_gamma"].mean().to_dict()
gam_per_d  = (df_gamma_src[df_gamma_src["source_test"] == perc_src]
              .groupby(["model","fb_exp"], observed=True)["f_gamma"].mean().to_dict())
rr_m = df.groupby(["model","source_test","fb_exp"], observed=True)["rating_cen"].mean().to_dict()
rr_s = df.groupby(["model","source_test","fb_exp"], observed=True)["rating_cen"].sem().to_dict()
conf_levels = sorted(df["confidence_num"].dropna().astype(int).unique())


def _bar(ax, d, ylabel="", ylim=(0,1)):
    for fi, fb in enumerate(FB_VALS):
        vals = [d.get((m, fb), np.nan) for m in MODEL_ORDER]
        ax.bar(x + (fi-.5)*bar_w, vals, width=bar_w,
               color=FB_PALETTE[fb], label=FB_LABELS[fb],
               alpha=0.88, edgecolor="white", lw=0.6)
    ax.set_xticks(x)
    ax.set_xticklabels(MODEL_LABELS, fontsize=9, fontweight="bold",
                       rotation=45, ha="right", rotation_mode="anchor")
    ax.set_xlim(-.6, len(MODEL_ORDER)-.4)
    ax.set_ylabel(ylabel, fontsize=11, fontweight="bold")
    ax.set_ylim(*ylim)


def _ann(ax, letter, title):
    ax.text(-.15, 1.08, letter, transform=ax.transAxes,
            fontsize=14, fontweight="bold", va="top")
    ax.set_title(title, pad=8, fontsize=12, fontweight="bold")


fig = plt.figure(figsize=(18, 11))
gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=.65, wspace=.42,
                        left=.07, right=.97, top=.92, bottom=.14)

ax_a = fig.add_subplot(gs[0,0])
_bar(ax_a, rh_means, "RH Rate (perceived only)")
ax_a.legend(title="Feedback", fontsize=8, loc="upper left")
_ann(ax_a, "A", "Reading Hallucination")

ax_b = fig.add_subplot(gs[0,1])
_bar(ax_b, acc_means, "Recognition Accuracy")
ax_b.legend(title="Feedback", fontsize=8, loc="lower right")
_ann(ax_b, "B", "Recognition Accuracy")

ax_c = fig.add_subplot(gs[0,2])
COLS = sns.color_palette("tab10", n_colors=len(MODEL_ORDER))
for mi, mdl in enumerate(MODEL_ORDER):
    sub = df[(df["model"]==mdl) & (df["source_test"]==perc_src)]
    if sub.empty:
        continue
    p = (sub["confidence_num"].dropna().astype(int)
         .value_counts(normalize=True).reindex(conf_levels, fill_value=0.0))
    ax_c.plot(p.index, p.values, color=COLS[mi], lw=1.4, alpha=.75,
              label=mdl.replace("-","-\n"))
ax_c.set_xlabel("Confidence Level", fontsize=11, fontweight="bold")
ax_c.set_ylabel("Proportion",       fontsize=11, fontweight="bold")
ax_c.set_xticks(conf_levels)
ax_c.legend(ncol=2, fontsize=7)
_ann(ax_c, "C", "Confidence Distribution")

ax_d = fig.add_subplot(gs[1,0])
_bar(ax_d, gam_all_d, "Fisher's Z (γ)", ylim=(-2,4))
ax_d.axhline(0, color="black", lw=.8, ls="--", alpha=.5)
ax_d.legend(title="Feedback", fontsize=8)
_ann(ax_d, "D", "Metacognitive γ (All)")

ax_e = fig.add_subplot(gs[1,1])
_bar(ax_e, gam_per_d, "Fisher's Z (γ)", ylim=(-2,5))
ax_e.axhline(0, color="black", lw=.8, ls="--", alpha=.5)
ax_e.legend(title="Feedback", fontsize=8)
_ann(ax_e, "E", "Metacognitive γ (Perceived)")

ax_f = fig.add_subplot(gs[1,2])
ls_map = ["-","--"]
for si, src in enumerate(src_cats):
    for fb in FB_VALS:
        means = [rr_m.get((ml,src,fb), np.nan) for ml in MODEL_ORDER]
        ses   = [rr_s.get((ml,src,fb), 0.)     for ml in MODEL_ORDER]
        ax_f.errorbar(x, means, yerr=ses, color=FB_PALETTE[fb], ls=ls_map[si],
                      lw=2., marker="o", ms=5, capsize=3, alpha=.88,
                      label=f"{FB_LABELS[fb]} · {src}")
ax_f.set_xticks(x)
ax_f.set_xticklabels(MODEL_LABELS, fontsize=9, fontweight="bold",
                     rotation=45, ha="right", rotation_mode="anchor")
ax_f.set_xlim(-.6, len(MODEL_ORDER)-.4)
ax_f.set_ylabel("Rating (centred, Mean ± SE)", fontsize=11, fontweight="bold")
ax_f.legend(fontsize=7, loc="lower right")
_ann(ax_f, "F", "Relatedness Rating")

fig.suptitle("Experiment 2 — Key Results (v3)", fontsize=14, fontweight="bold", y=.98)
plt.savefig("exp2_key_results_v3.pdf", dpi=300, bbox_inches="tight")
plt.savefig("exp2_key_results_v3.png", dpi=300, bbox_inches="tight")
plt.close('all')
print("Figure saved.")

---
## 15. Key Results Figure

Figure saved.


## Section 16: Summary: Preprocessing & Model Structure

In [23]:
# ─────────────────────────────────────────────────────────────────────────────
# 16. Summary table
# ─────────────────────────────────────────────────────────────────────────────
display(Markdown("---\n## 16. Summary"))
display(Markdown("""
**Preprocessing:**
- `order_c = order − 1`  (0 = first presentation, 1 = second)
- `rating_cen = rating − grand_mean`  (centred, not z-scored)

**Model structure per outcome:**

| Step | Comparison | What is tested |
|---|---|---|
| 1 | RE: `(1+source_test\\|trace)` vs `(1\\|trace)` | Random-slope necessity |
| 2 | FE: null → additive | Any fixed effects improve fit |
| 3 | FE: additive → interactive | 2-way interactions needed |

| Model | Trials | Family | Key fixed effects |
|---|---|---|---|
| 1. RH | perceived | Binomial | setsize×fb_exp, model, order_c |
| 2. Accuracy | all | Binomial | source_test, setsize, fb_exp, 2-ways, model, order_c, rating_cen |
| 2P. Accuracy | perceived | Binomial | setsize×fb_exp, model, order_c, rating_cen, **read_hallucination** |
| 3. Rating | all | Gaussian | source_test, setsize, fb_exp, 2-ways, model, order_c |
| 3P. Rating | perceived | Gaussian | setsize×fb_exp, model, order_c, **read_hallucination** |
| 4. Confidence | all | Gaussian | accuracy, source_test, setsize, fb_exp, 2-ways, model, order_c, rating_cen |
| 4P. Confidence | perceived | Gaussian | accuracy, setsize×fb_exp, model, order_c, rating_cen, **read_hallucination** |
| 5. γ | all | Gaussian | source_test, setsize, fb_exp, 2-ways, model |
| 5P. γ | perceived | Gaussian | setsize×fb_exp, model, **rh_mean** |

**Post-hoc contrasts (FDR-corrected):**
H1 source_test · H2 fb_exp · H3 source_test×fb_exp · H4 model · covariates (slopes)
"""))
print("Analysis complete.")

---
## 16. Summary


**Preprocessing:**
- `order_c = order − 1`  (0 = first presentation, 1 = second)
- `rating_cen = rating − grand_mean`  (centred, not z-scored)

**Model structure per outcome:**

| Step | Comparison | What is tested |
|---|---|---|
| 1 | RE: `(1+source_test\|trace)` vs `(1\|trace)` | Random-slope necessity |
| 2 | FE: null → additive | Any fixed effects improve fit |
| 3 | FE: additive → interactive | 2-way interactions needed |

| Model | Trials | Family | Key fixed effects |
|---|---|---|---|
| 1. RH | perceived | Binomial | setsize×fb_exp, model, order_c |
| 2. Accuracy | all | Binomial | source_test, setsize, fb_exp, 2-ways, model, order_c, rating_cen |
| 2P. Accuracy | perceived | Binomial | setsize×fb_exp, model, order_c, rating_cen, **read_hallucination** |
| 3. Rating | all | Gaussian | source_test, setsize, fb_exp, 2-ways, model, order_c |
| 3P. Rating | perceived | Gaussian | setsize×fb_exp, model, order_c, **read_hallucination** |
| 4. Confidence | all | Gaussian | accuracy, source_test, setsize, fb_exp, 2-ways, model, order_c, rating_cen |
| 4P. Confidence | perceived | Gaussian | accuracy, setsize×fb_exp, model, order_c, rating_cen, **read_hallucination** |
| 5. γ | all | Gaussian | source_test, setsize, fb_exp, 2-ways, model |
| 5P. γ | perceived | Gaussian | setsize×fb_exp, model, **rh_mean** |

**Post-hoc contrasts (FDR-corrected):**
H1 source_test · H2 fb_exp · H3 source_test×fb_exp · H4 model · covariates (slopes)


Analysis complete.
