#!/usr/bin/env python3

content = """# Reality Monitoring (RM) Task with LLMs: Comprehensive Description

## Executive Summary

This document describes a series of experiments investigating how Large Language Models (LLMs) perform on Reality Monitoring tasks. Reality Monitoring refers to the ability to discriminate between internally generated information (imagination, hallucinations) and externally perceived information (real, known facts). The study examines LLM performance on word-pair relatedness judgment tasks where models must generate words and distinguish between real words and their own hallucinations.

---

## 1. Project Overview

### 1.1 Research Objective
Evaluate and measure how LLMs maintain reality monitoring capabilities when performing word association tasks, including:
- Generating semantically related words to given word pairs
- Rating relatedness between word pairs (0-100 scale)
- Discriminating between externally known words and internally generated/hallucinated words
- Assessing confidence in their own judgments

### 1.2 Key Constructs
- **Word Pair**: Two related words (word_1 and word_2) that may share phonetic, semantic, or categorical relationships
- **Relatedness Rating**: Numeric judgment (0-100) indicating how related two words are
- **Source Judgment**: Binary classification—is word_2 external (real) or internal (generated/hallucinated)?
- **Confidence Level**: Numeric rating (1-6) of confidence in the source judgment
- **Compliance**: Whether the model followed task instructions (trial_compliance)
- **Hallucination**: Whether the model correctly identified its own generated words vs. real words

---

## 2. Experimental Design

### 2.1 Experiments Overview

The study includes multiple experiments with varying conditions:

| Experiment | Description | Tasks |
|-----------|-------------|-------|
| **Exp 1** | Baseline reality monitoring with word pairs operated on by 2 operators | Single-turn, 144 trials |
| **Exp 2** | Extended performance under different feedback conditions | Multiple variants with/without feedback |
| **Exp 2_R** | Replication of Exp 2 | Repeated measurement for robustness |

### 2.2 Task Variants

#### 2.2.1 Core Tasks
- **rm_2op**: 2-operator task (baseline)
- **rm_2op_r**: 2-operator task with repeat/replication
- **rm_2op_tc**: 2-operator task with thought chains
- **rm_2op_tc_r**: 2-operator task with thought chains (replicated)

#### 2.2.2 Feedback Conditions
- **No Feedback**: Models receive only the task instructions with no feedback
- **With Feedback**: Models receive feedback on previous trials to guide subsequent responses

#### 2.2.3 Convo Variants
- **Single Turn**: One interaction per trial
- **Convo**: Multi-turn conversation for extended context

---

## 3. Task Specifications

### 3.1 Task Structure

Each trial consists of the following components:

#### Component 1: Word Pair Identification (WORD_PAIR_TASK)
- **Input**: word_1 (given) and word_2 (may be provided or blank "______")
- **Action**: 
  - If word_2 is a valid English word, identify and report it as-is
  - If word_2 is blank, imagine and generate a valid English word that completes the pair
- **Constraints** (what is prohibited):
  - Using word_1 in any form or variation
  - Creating compound words
  - Using symbols, numbers, or mathematical equations
  - Using words outside standard English dictionaries
- **Permitted**: Singular English dictionary words not in the prohibited list

#### Component 2: Relatedness Rating (RELATEDNESS_RATING_BETWEEN_WORD_1_AND_WORD_2)
- **Output**: Numeric value from 0 to 100
- **Scale Definitions**:
  - 0: Words are not related at all
  - 50: Words have moderate/intermediate relatedness
  - 100: Words are very highly related
- **Basis for Judgment**: Rating should consider:
  - Phonetic similarity (how words sound)
  - Semantic similarity (meaning and concept)
  - Categorical relationships (shared categories or associations)
- **Constraint**: Strictly use 0-100 range

#### Component 3: Generation Type Judgment (JUDGE_GENERATION_TYPE_OF_WORD_2)
- **Output**: Binary classification—"external" or "internal"
- **Definitions**:
  - **External**: word_2 is a real, known English word from standard dictionaries
  - **Internal**: word_2 was generated by the model or represents model hallucination
- **Purpose**: Tests whether the model can distinguish its own generated words from real vocabulary

#### Component 4: Confidence Rating (CONFIDENCE_ON_JUDGEMENT_OF_GENERATION_TYPE)
- **Output**: Numeric value from 1 to 6
- **Scale Definitions**:
  - 1: Very low confidence in the source judgment
  - 3: Moderate confidence in the source judgment
  - 6: Very high confidence in the source judgment
- **Purpose**: Captures model uncertainty in distinguishing real from generated words

---

## 4. Data Structure and Variables

### 4.1 Trial-Level Data Format

Each row in the trial data represents one task trial with the following key variables:

| Variable | Type | Description | Example |
|----------|------|-------------|---------|
| **tridx** | Integer | Trial index/number within experiment | 1, 2, 3, ... |
| **trcode** | String | Trial code identifier | "perceived_2", "halluc_5" |
| **taskname** | String | Task identifier | "zs_rm_2op" |
| **source** | Categorical | True source of word_2: "perceived" (external) or "generated" (internal) | "perceived", "generated" |
| **trace** | String | Additional trace/metadata | Empty or descriptive |
| **word_1** | String | First word in pair (given to model) | "sugar", "chair", "sky" |
| **word_2** | String | Second word in pair (actual/ground truth) | "sweet", "cushion", "airplane" |
| **Word_2** | String | Model's response for word_2 | "sweet", "cushion", "airplane" |
| **rating** | Numeric (0-100) | Model's relatedness rating | 95.0, 75.0, 65.0 |
| **Judgment** | Categorical | Model's source judgment | "external", "internal" |
| **confidence** | Numeric (1-6) | Model's confidence in judgment | 6.0, 5.0, 4.0 |
| **model** | String | LLM model used | "Gemma3:12b", "Gemma3:27b" |
| **task** | String | Task variant | "rm_2op", "rm_2op_tc", etc. |
| **memory** | Categorical | Memory condition | "SingleTurn", "MultiTurn", "WithFeedback" |
| **experiment** | String | Experiment identifier | "task_1", "task_2" |
| **study** | Categorical | Study type | External, Internal, Mixed |
| **order** | Integer | Order of trial within session | 1, 2, 3, ... |
| **corrAns** | Binary | Whether judgment matches ground truth (1=correct, 0=incorrect) | 1, 0 |
| **word2acc** | Binary | Whether word_2 response is correct (1=correct, 0=incorrect) | 1, 0 |
| **accuracy** | Numeric (0-1) | Overall accuracy on trial | 1, 0, 0.5 |
| **trial_compliance** | Binary | Whether model followed task instructions (1=compliant, 0=non-compliant) | 1, 0 |
| **reading_hallucination** | Binary | Whether response contains hallucination (1=hallucinated, 0=genuine) | 1, 0 |
| **total_trials** | Integer | Total number of trials in experiment | 144 |

### 4.2 Group-Level Aggregated Data

Group-level data aggregates trial-level metrics by model, task, and condition:

| Variable | Type | Description |
|----------|------|-------------|
| **model** | Categorical | LLM model identifier |
| **task** | Categorical | Task identifier |
| **mean_rating** | Numeric | Average relatedness rating across trials |
| **std_rating** | Numeric | Standard deviation of ratings |
| **judgment_accuracy** | Numeric (0-1) | Proportion of correct source judgments |
| **compliance_rate** | Numeric (0-1) | Proportion of trials with compliant responses |
| **hallucination_rate** | Numeric (0-1) | Proportion of trials with detected hallucinations |
| **mean_confidence** | Numeric (1-6) | Average confidence rating |
| **calibration** | Numeric | Alignment between confidence and accuracy |

---

## 5. Performance Metrics and Calculations

### 5.1 Primary Metrics

#### 5.1.1 Source Judgment Accuracy (corrAns)
- **Definition**: Whether the model correctly identified whether word_2 is external (real) or internal (generated)
- **Calculation**: Binary comparison of judgment ("external"/"internal") against ground truth (source variable)
- **Interpretation**: 1 = correct discrimination, 0 = incorrect (hallucination or false reality attribution)

#### 5.1.2 Word Accuracy (word2acc)
- **Definition**: Whether the model's generated/selected word_2 matches the expected word
- **Calculation**: Exact string match between Word_2 (model response) and word_2 (ground truth)
- **Interpretation**: 1 = accurate word generation/selection, 0 = incorrect word

#### 5.1.3 Trial Accuracy
- **Definition**: Overall trial performance combining word accuracy and judgment accuracy
- **Calculation**: Average of word2acc and corrAns
- **Range**: 0 (complete failure) to 1 (perfect performance)

#### 5.1.4 Trial Compliance
- **Definition**: Whether the model adhered to task instructions and constraints
- **Checks Include**:
  - Word_2 response is a valid English word
  - Rating is within 0-100 range
  - Judgment is "external" or "internal"
  - Confidence is within 1-6 range
- **Interpretation**: 1 = fully compliant, 0 = violated one or more constraints

#### 5.1.5 Reading Hallucination
- **Definition**: Whether the model response contains factual inaccuracies or invented information
- **Calculation**: Comparison of model's word and judgment against ground truth and logical consistency
- **Interpretation**: 1 = hallucination detected, 0 = no hallucination

### 5.2 Derived Metrics

#### 5.2.1 Calibration
- **Definition**: Alignment between model confidence and actual accuracy
- **Calculation**: Correlation between confidence ratings and accuracy (corrAns)
- **Interpretation**:
  - High positive correlation: Model is well-calibrated (confident when correct)
  - Near-zero correlation: Model is uncalibrated (confidence unrelated to accuracy)
  - Negative correlation: Model is miscalibrated (confident when incorrect)

#### 5.2.2 Hallucination Rate
- **Definition**: Proportion of trials where the model hallucinated
- **Calculation**: sum(reading_hallucination) / total_trials
- **Interpretation**: Higher values indicate greater tendency to hallucinate

#### 5.2.3 Compliance Rate
- **Definition**: Proportion of trials with full instruction compliance
- **Calculation**: sum(trial_compliance) / total_trials
- **Interpretation**: Indicates reliability of model responses

---

## 6. Analysis Guidelines for LLMs

When analyzing this data, follow these guidelines:

### 6.1 Data Validation
1. Verify all numeric variables (rating, confidence, accuracy) are within expected ranges
2. Check for missing or null values and document their frequency
3. Confirm trial counts match expected experiment design
4. Validate that ground truth labels (source) are correctly coded

### 6.2 Performance Analysis
1. Calculate accuracy metrics separately for "external" and "internal" sources to detect source-specific biases
2. Compare performance across different models and task variants
3. Analyze rating distributions to detect response biases (e.g., always rating high)
4. Examine confidence calibration separately for correct vs. incorrect trials

### 6.3 Hallucination Analysis
1. Identify trial patterns where hallucination tends to occur
2. Analyze whether hallucinations correlate with confidence levels
3. Examine model-specific hallucination rates for comparative analysis
4. Consider whether word pairing difficulty influences hallucination rates

### 6.4 Compliance Analysis
1. Identify specific types of constraint violations
2. Determine if compliance decreases across trial order
3. Analyze compliance by task variant and memory condition
4. Assess whether non-compliance correlates with reduced accuracy

### 6.5 Statistical Testing
1. Use appropriate tests for comparing categorical outcomes (e.g., Chi-square for accuracy differences)
2. Use ANOVA or regression for continuous variables (rating, confidence)
3. Control for multiple comparisons when testing multiple hypotheses
4. Report effect sizes alongside statistical significance
5. Consider mixed-effects models to account for trial clustering within participants/models

---

## 7. Data Files Reference

### 7.1 Trial-Level Data
- **exp1_trial_data.csv**: Experiment 1 individual trial records
- **exp2_trial_data.csv**: Experiment 2 individual trial records
- **rmai_exp100_2.csv**: Extended Experiment 2 with additional model variants
- **rmai_exp100_2_r.csv**: Experiment 2 replication data

### 7.2 Aggregated Data
- **exp1_group_level.csv**: Experiment 1 group-level summaries
- **exp2_group_level.csv**: Experiment 2 group-level summaries

### 7.3 Raw Task Specifications
- **data/raw/run_tasks/**: Task definition JSON files specifying instructions for each task variant

---

## 8. Key Research Questions

When analyzing this data, address:

1. **Reality Monitoring Capability**: Can LLMs accurately distinguish between externally known words and internally generated/hallucinated words?

2. **Model Variation**: Do different LLM models (Gemma variants) differ in reality monitoring accuracy?

3. **Confidence Calibration**: Are models appropriately confident in their judgments? Does confidence align with accuracy?

4. **Task Complexity**: Does adding complexity (thought chains, feedback, multi-turn context) improve or degrade performance?

5. **Hallucination Patterns**: Under what conditions do hallucinations occur? Are they random or systematic?

6. **Instruction Compliance**: How well do models follow task constraints? Does non-compliance correlate with performance?

---

## 9. Metadata and Coding Schemes

### 9.1 Source Coding
- **"perceived"**: Word represents externally known, dictionary-validated word
- **"generated"**: Word was generated by the model or represents model-created/hallucinated word

### 9.2 Judgment Coding
- **"external"**: Model judged word_2 as real/externally known
- **"internal"**: Model judged word_2 as generated/hallucinated

### 9.3 Memory Condition Coding
- **"SingleTurn"**: Single interaction per trial, no context carried forward
- **"WithFeedback"**: Model receives feedback about previous trial performance
- **"MultiTurn"**: Multi-turn conversation within a trial

### 9.4 Model Coding
- **"Gemma3:12b"**: Gemma 3 model with 12-billion parameters
- **"Gemma3:27b"**: Gemma 3 model with 27-billion parameters
- Additional models may be present in extended datasets

---

## 10. Data Analysis Workflow

### Typical Analysis Steps:

1. **Load & Inspect**: Load trial-level data and verify structure and coding
2. **Validate**: Check for missing values, data types, and range violations
3. **Aggregate**: Calculate performance metrics by model, task, and condition if not pre-calculated
4. **Explore**: Examine distributions, correlations, and patterns
5. **Compare**: Conduct comparative analyses across models and task variants
6. **Interpret**: Contextualize findings within reality monitoring framework
7. **Report**: Generate summary statistics and visualizations

---

## 11. Important Notes for LLM Analyzers

- **Interpretation Context**: The terms "external" and "internal" refer to the model's knowledge of real English words vs. generated/hallucinated words, not human reality monitoring terminology
- **Accuracy Asymmetry**: Models may perform differently when judging truly external vs. internally generated words
- **Confidence Validity**: Confidence ratings should be interpreted cautiously; they represent the model's uncertainty estimation, not ground-truth reliability
- **Hallucination Detection**: The "reading_hallucination" variable captures detected inconsistencies; some hallucinations may go undetected
- **Task Difficulty**: Some word pairs are inherently more difficult to rate and judge; trial-level analysis should account for potential systematic item effects

---

## 12. Glossary

| Term | Definition |
|------|-----------|
| **Reality Monitoring** | Cognitive ability to distinguish information from external perception vs. internal generation |
| **Hallucination** | Model generation of false or unsupported information |
| **Compliance** | Adherence to task instructions and specified constraints |
| **Calibration** | Alignment between a model's confidence and its actual accuracy |
| **Source Judgment** | Classification of information origin (external vs. internal) |
| **Relatedness** | Degree of semantic, phonetic, or categorical connection between two words |
| **Ground Truth** | Verified, correct answer or source label for a trial |

---

## Document Metadata

- **Version**: 1.0
- **Last Updated**: March 28, 2026
- **Project**: Reality Monitoring with LLMs (RMLLM)
- **Author**: Research Team
- **Purpose**: LLM-friendly comprehensive task and data specification for data analysis
"""

import os

repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out_path = os.path.join(repo_root, "docs", "task_description.md")
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w") as f:
    f.write(content)
print("SUCCESS: File created")
